// ═══════════════════════════════════════════════════════════════
// 🏠 Family HQ — i18n dictionary (v8.34.0)
// ═══════════════════════════════════════════════════════════════
// Loaded BEFORE app.js via <script src="/static/lang.js?v=N"> in index.html.
// app.js reads this via `window.LANG`.
//
// ── Key naming convention (flat, namespace-prefixed):
//   nav_*      bottom-nav labels  (nav_home, nav_tasks, ...)
//   tt_<id>_t  page title         (tt_home_t, tt_tasks_t, ...)
//   tt_<id>_s  page subtitle      (tt_home_s, tt_tasks_s, ...)
//   btn_*      common buttons     (btn_save, btn_cancel, ...)
//   set_*      Settings labels    (set_family, set_language, ...)
//   mt_*       modal titles       (mt_add_task, mt_edit_plant, ...)
//   f_*        form field labels  (f_name, f_amount, ...)
//   p_*        priority labels    (p_low, p_normal, p_high)
//   m_*        Money-tab          (m_transactions, m_analytics, ...)
//   pl_*       Plants-tab         (pl_thirsty, pl_water, ...)
//   tk_*       Tasks sub-sections (tk_overdue, tk_caught_up, ...)
//   ts_*       toasts             (ts_saved, ts_deleted, ...)
//   es_*       empty states       (es_no_tasks_t, es_no_tasks_s, ...)
//   cf_*       confirm prompts    (cf_delete_task, cf_leave_family, ...)
//   g_*        generic / shared   (g_today, g_loading, g_done, ...)
//
// ── Pluralization (Intl.PluralRules):
//   For count-dependent strings, define keys with suffixes _one, _few, _many,
//   _other. Use the `trn(base_key, n)` helper in app.js — it picks the right
//   form for the current locale automatically.
//
//   English needs: _one (n==1), _other (everything else)
//   Russian needs: _one (1, 21, 31...), _few (2-4, 22-24...), _many (5-20, 25-30...), _other (fractional)
//
//   Example: `trn("g_in_days_full", 5)` → "5 дней" (ru/many) or "in 5 days" (en/other)

window.LANG = {
  en: {
    // Nav
    nav_home: "Home", nav_tasks: "Tasks", nav_words: "Words", nav_money: "Money", nav_profile: "Profile",
    nav_shop: "Shop", nav_cooking: "Cooking", nav_life: "Life", nav_trainings: "Gym", nav_plants: "Plants", nav_birthdays: "Birthdays", nav_clean: "Clean", nav_subs: "Subs", nav_settings: "Settings",
    // Life tab (v8.51.0)
    tt_life_t: "Life", tt_life_s: "Your living balance",
    life_you: "You", life_us: "Us",
    life_hint_personal: "Tap an area to grow it · hold empty space to edit",
    life_hint_family: "Your connection — tap an area · hold empty space to edit",
    life_hint_area: "Tap a habit · hold empty space to add & edit",
    life_hint_area_empty: "Hold empty space to add your first habit",
    life_new_habit: "Plant a habit",
    life_habit: "Habit",
    life_habit_name: "Name",
    life_habit_ph: "e.g. Morning walk",
    life_type: "Type",
    life_type_build: "Build", life_type_maintain: "Maintain", life_type_reduce: "Reduce",
    life_frequency: "How often",
    life_daily: "Daily",
    life_streak: "Streak", life_consistency: "Consistency",
    life_mark_done: "Mark as done", life_done_today: "Done today",
    life_name_required: "Give it a name",
    life_delete_confirm: "Delete this habit?",
    life_edit_node: "Edit area", life_node_name: "Name", life_node_reset: "Reset to default",
    life_ideas: "Ideas", life_ideas_sub: "Tap + to plant any of these",
    life_thinking: "Thinking of ideas for you…", life_no_ideas: "Couldn't get ideas right now — try again",
    life_edit_habit: "Edit habit",
    life_edit_on: "Editing — tap a node to edit · tap empty space to finish",
    life_journey: "Journey", life_balance: "Balance", life_connection: "Connection",
    life_j_activity: "Activity · last 30 days", life_j_habits: "Habits", life_j_done_today: "Done today",
    life_j_this_week: "This week", life_j_best_streak: "Best streak",
    life_j_empty: "Plant a few habits to see your journey grow",
    life_challenges: "Challenges", life_ch_current: "Current", life_ch_completed: "Done",
    life_ch_new: "New", life_ch_goal: "Goal", life_ch_kind_count: "Count", life_ch_kind_streak: "Streak",
    life_ch_kind_score: "Score", life_ch_until: "Until…", life_ch_ended: "Ended",
    life_ch_target: "Target", life_ch_times: "times", life_ch_days_row: "days in a row",
    life_ch_track: "Track", life_ch_anything: "Anything", life_ch_spheres: "Spheres", life_ch_habits: "Habits",
    life_ch_period: "Period", life_ch_days: "days", life_ch_create: "Create challenge",
    life_ch_title_ph: "e.g. 5 workouts this week", life_ch_done: "Done", life_ch_failed: "Missed",
    life_ch_days_left_one: "{n} day left", life_ch_days_left_other: "{n} days left",
    // Love Points
    love_title: "Love Points", love_stats: "Stats", love_stats_title: "Love Points · this month",
    love_days_left_one: "{n} day left this month", love_days_left_other: "{n} days left this month",
    love_award_to: "Give %s a point", love_reason_ph: "What for?", love_give: "Give point",
    love_from: "by %s", love_a_point: "a point", love_no_points: "No points yet this month — be the first 💞",
    just_now: "just now", m_ago: "m ago", h_ago: "h ago",
    life_ch_empty_current: "No active challenges — create one ✨",
    life_ch_empty_completed: "Nothing completed yet",
    life_ch_delete_confirm: "Delete this challenge?",
    life_ch_participants: "Participants", life_ch_participants_hint: "Pick who's in — each tracked separately. Lives under Family.",
    life_new_sphere: "New sphere", life_add_sphere: "Add sphere", life_sphere_ph: "e.g. Travel",
    life_color: "Color", life_delete_sphere: "Delete sphere",
    life_delete_sphere_confirm: "Delete this sphere and all its habits?",
    // Page headers (title + subtitle)
    tt_home_t: "Family HQ", tt_home_s: "Everything at a glance",
    tt_tasks_t: "Tasks", tt_tasks_s: "Manage & assign",
    tt_shop_t: "Shopping", tt_shop_s: "Shared list",
    tt_trainings_t: "Trainings", tt_trainings_s: "Workouts & progress",
    tt_words_t: "Words", tt_words_s: "Vocabulary learning",
    tt_plants_t: "Plants", tt_plants_s: "Care & watering",
    tt_cooking_t: "Cooking", tt_cooking_s: "Dishes & ingredient costs",
    tt_money_t: "Money", tt_money_s: "Budget & subs",
    tt_profile_t: "Profile", tt_profile_s: "Personal stats",
    tt_events_t: "Events", tt_events_s: "Schedule",
    tt_birthdays_t: "Birthdays", tt_birthdays_s: "Never forget",
    tt_clean_t: "Cleaning", tt_clean_s: "Apartment zones",
    tt_settings_t: "Settings", tt_settings_s: "Customize",
    tt_subs_t: "Subscriptions", tt_subs_s: "Monthly payments",
    tt_recurring_t: "Recurring", tt_recurring_s: "Repeating tasks",
    // Common buttons
    btn_add: "Add", btn_save: "Save", btn_cancel: "Cancel", btn_delete: "Delete",
    btn_edit: "Edit", btn_close: "Close", btn_done: "Done", btn_ok: "OK", btn_yes: "Yes", btn_no: "No",
    btn_back: "Back", btn_next: "Next", btn_share: "Share",
    btn_create: "Create", btn_update: "Update", btn_join: "Join",
    btn_remove: "Remove", btn_set: "Set", btn_start: "Start",
    btn_finish: "Finish", btn_apply: "Apply", btn_reset: "Reset",
    btn_take_photo: "Take photo", btn_choose_photo: "Choose photo",
    // Settings sections
    set_family: "Family", set_members: "Members", set_appearance: "Appearance",
    set_theme: "Theme", set_language: "Language", set_notifications: "Notifications",
    set_developer: "Developer", set_invite_code: "Invite Code",
    set_share_invite: "Share invite", set_leave_family: "Leave Family",
    set_share_hint: "Share this with new members",
    set_money: "Money", set_categories: "Categories", set_learning: "Learning",
    set_integrations: "Integrations", set_learning_lang: "Learning language",
    set_words_editor: "Words editor", set_reset_progress: "Reset my progress",
    set_morning_digest: "Morning Digest", set_morning_digest_sub: "Sections & order",
    set_trello_sync: "Trello Sync",
    set_debug: "Debug Mode", set_words_editor_sub: "Edit cards · add images",
    set_reset_progress_sub: "Wipe my learned/learning state",
    // Generic
    g_loading: "Loading…", g_today: "Today", g_yesterday: "Yesterday", g_tomorrow: "Tomorrow",
    g_upcoming: "Upcoming", g_completed: "Completed", g_all: "All",
    g_active: "Active", g_recurring: "Recurring", g_events: "Events",
    g_calendar: "Calendar", g_upcoming_7: "Upcoming 7 Days",
    g_tasks: "Tasks", g_subscriptions: "Subscriptions", g_birthdays: "Birthdays",
    g_feels: "feels", g_today_bday: "Today! 🎉", g_no_items: "Nothing yet",
    g_by_category: "By Category", g_limits: "Limits", g_menu: "Menu",
    g_morning: "Morning", g_afternoon: "Afternoon", g_evening: "Evening",
    g_enter_code: "Enter 6-character code",
    g_reminders: "Reminders", g_date_of_birth: "Date of Birth",
    g_assigned_to: "Assigned to", g_assign_to: "Assign to",
    g_start: "Start", g_time: "Time", g_end_opt: "End (optional)",
    g_schedule: "Schedule", g_daily: "Daily", g_weekly: "Weekly", g_monthly: "Monthly",
    g_days: "Days", g_day_of_month: "Day of month", g_what_to_do: "What needs to be done?",
    g_due_date: "Due Date", g_who: "Who",
    g_every_day: "Every day", g_paused: "Paused", g_done: "Done", g_filter_all: "All",
    // Pluralized — picked via trn() helper using Intl.PluralRules
    g_in_days_short_one: "in {n}d", g_in_days_short_other: "in {n}d",
    g_in_days_full_one: "in {n} day", g_in_days_full_other: "in {n} days",
    // Money
    m_transactions: "Transactions", m_analytics: "Analytics",
    m_income: "Income", m_expense: "Expense", m_balance: "Balance",
    m_this_month: "This Month",
    // Plants
    pl_thirsty: "Wants water", pl_soon: "Water soon", pl_healthy: "Healthy",
    pl_water: "Water", pl_thanks: "Thank you!", pl_add: "Add",
    pl_care_for: "Care for", pl_water_every: "Water every",
    pl_growth_timeline: "Growth timeline", pl_care_tips: "Care tips",
    // Update + AI health check (v8.46.0)
    pl_update: "Update", pl_analyzing: "Analyzing photo…",
    pl_take_photo: "Take photo", pl_take_photo_d: "Use the camera now",
    pl_from_gallery: "From gallery", pl_from_gallery_d: "Pick an existing photo",
    pl_camera_unavail: "Camera unavailable",
    pl_h_title: "Plant health check",
    pl_h_healthy: "Looks healthy", pl_h_concern: "Needs attention", pl_h_critical: "Critical",
    pl_h_issues: "What I see", pl_h_advice: "What to do",
    pl_h_no_issues: "No issues spotted — keep doing what you're doing.",
    pl_h_view: "View previous health check",
    // Modal titles
    mt_add_task: "Add Task", mt_edit_task: "Edit Task",
    mt_add_event: "Add Event", mt_edit_event: "Edit Event",
    mt_add_expense: "Add Expense", mt_add_income: "Add Income",
    mt_add_shop: "Add Item", mt_add_sub: "Add Subscription",
    mt_add_bday: "Add Birthday", mt_add_recur: "Add Recurring",
    mt_add_plant: "Add plant", mt_edit_plant: "Edit plant",
    mt_more: "More", mt_photo: "Photo", mt_which_one: "Which one is it?",
    mt_create_family: "Create Family", mt_join_family: "Join Family",
    mt_new_folder: "New Folder", mt_categories: "Categories",
    mt_choose_city: "Choose city", mt_stats: "Stats",
    mt_morning_digest: "Morning Digest", mt_learning_lang: "Learning language",
    mt_words: "Words", mt_edit_word: "Edit word",
    mt_start_workout: "Start Workout", mt_new_template: "New Template",
    mt_edit_template: "Edit Template", mt_edit_set: "Edit Set",
    mt_edit_workout: "Edit Workout", mt_add_exercise: "Add exercise",
    mt_progress: "Progress", mt_edit_bday: "Edit Birthday", mt_add_zone: "Add Zone",
    mt_choose_theme: "Choose theme", mt_custom_theme: "Custom Theme",
    mt_new_cat: "New Category", mt_edit_cat: "Edit Category",
    mt_new_exercise: "New exercise", mt_workout: "Workout",
    // Form fields
    f_title: "Title", f_text: "Text", f_amount: "Amount", f_currency: "Currency",
    f_category: "Category", f_description: "Description", f_date: "Date",
    f_priority: "Priority", f_assigned_to: "Assigned to", f_when: "When",
    f_repeat: "Repeat", f_emoji: "Emoji", f_name: "Name", f_quantity: "Quantity",
    f_price: "Price", f_folder: "Folder", f_notes: "Notes", f_color: "Color",
    f_image: "Image", f_caption: "Caption",
    // Priorities
    p_low: "Low", p_normal: "Normal", p_high: "High",
    // Confirms
    cf_delete_task: "Delete this task?", cf_delete_event: "Delete this event?",
    cf_delete_transaction: "Delete this transaction?",
    cf_delete_generic: "Delete?", cf_leave_family: "Leave family?",
    // Tasks tab sections
    tk_overdue: "Overdue", tk_high_pri: "High Priority", tk_this_week: "This Week",
    tk_rest: "Rest", tk_caught_up: "All caught up! 🎉",
    tk_no_recur_t: "No recurring tasks", tk_no_recur_s: "Tap + to create",
    // Toasts
    ts_saved: "Saved", ts_deleted: "Deleted", ts_error: "Error",
    ts_network: "Network error", ts_copied: "Copied",
    ts_save_failed: "Save failed", ts_upload_failed: "Upload failed",
    ts_upload_error: "Upload error", ts_failed: "Failed",
    ts_image_saved: "Image saved", ts_image_removed: "Image removed",
    ts_photo_added: "Photo added", ts_photo_deleted: "Photo deleted",
    ts_caption_saved: "Caption saved", ts_too_large: "Too large (>15 MB)",
    ts_word_required: "Word required on both sides",
    ts_watering_undone: "↩ Watering undone",
    // Empty states (icon + title + subtitle)
    es_no_tasks_t: "No tasks yet", es_no_tasks_s: "Tap + to add one",
    es_no_events_t: "No events", es_no_events_s: "Tap + Add Event to start",
    es_no_birthdays_t: "No birthdays", es_no_birthdays_s: "Add below",
    es_no_subs_t: "No subscriptions", es_no_subs_s: "Add below",
    es_no_zones_t: "No zones yet", es_no_zones_s: "Add zones below",
    es_no_txs_t: "No transactions", es_no_txs_s: "Tap + to add",
    es_no_shop_t: "List is empty", es_no_shop_s: "Tap + to add",
    es_no_stock_t: "Nothing in stock", es_no_stock_s: "Buy items to see them here",
    es_no_match_t: "No matches", es_no_match_s: "Try a different search",
    // Days of week (short + full) and months (full)
    dow_short_sun: "Sun", dow_short_mon: "Mon", dow_short_tue: "Tue", dow_short_wed: "Wed",
    dow_short_thu: "Thu", dow_short_fri: "Fri", dow_short_sat: "Sat",
    dow_full_sun: "Sunday", dow_full_mon: "Monday", dow_full_tue: "Tuesday", dow_full_wed: "Wednesday",
    dow_full_thu: "Thursday", dow_full_fri: "Friday", dow_full_sat: "Saturday",
    mo_full_1: "January", mo_full_2: "February", mo_full_3: "March", mo_full_4: "April",
    mo_full_5: "May", mo_full_6: "June", mo_full_7: "July", mo_full_8: "August",
    mo_full_9: "September", mo_full_10: "October", mo_full_11: "November", mo_full_12: "December",
    mo_short_1: "Jan", mo_short_2: "Feb", mo_short_3: "Mar", mo_short_4: "Apr",
    mo_short_5: "May", mo_short_6: "Jun", mo_short_7: "Jul", mo_short_8: "Aug",
    mo_short_9: "Sep", mo_short_10: "Oct", mo_short_11: "Nov", mo_short_12: "Dec",
    // Theme names
    th_midnight: "Midnight", th_dawn: "Dawn", th_forest: "Forest", th_ocean: "Ocean",
    th_rose: "Rosé", th_chalk: "Chalk", th_onyx: "Onyx", th_lavender: "Lavender",
    th_sunset: "Sunset", th_custom: "Custom",
    // Words / Vocabulary tab
    wd_session_complete: "Session complete!",
    wd_next_session: "Next session",
    wd_correct_of: "{n} of {total} correct",
    wd_dont_know: "Don't know",
    wd_check: "Check",
    wd_no_learned_t: "No learned words yet",
    wd_no_learned_s: "Keep practising",
    wd_no_mistakes_t: "No mistakes yet",
    wd_no_mistakes_s: "Nice work!",
    wd_now_learning_en: "Now learning English",
    wd_now_learning_ru: "Now learning Russian",
    wd_reset_confirm: "Reset all your Words progress for {lang}?\n\nThis wipes your learned/learning state for the language you're currently studying. Other family members are unaffected.",
    wd_load_failed: "Failed to load.",
    wd_english: "English", wd_russian: "Russian",
    // Plants extras
    pl_no_plants_t: "No plants yet",
    pl_no_plants_s: "Tap + Add above and snap a photo — AI will identify it",
    pl_pick_photo: "Take photo or choose from gallery",
    pl_tap_to_change: "Tap to change",
    pl_add_photo_short: "Add photo",
    pl_replace_photo: "Replace photo",
    pl_delete_plant: "Delete plant",
    pl_delete_photo_confirm: "Delete this photo?",
    pl_delete_plant_confirm: "Delete {name}? This can't be undone.",
    pl_no_waterings_window: "No waterings logged in this window",
    pl_days_unit: "days",
    pl_caption: "Caption",
    // Weather widget
    wx_no_location: "No location",
    wx_set_city: "Set your city to see the forecast",
    wx_choose_city: "Choose city",
    wx_no_forecast: "No forecast data",
    wx_no_results: "No matches",
    // Generic prompts
    g_close: "Close", g_remove_image_confirm: "Remove image?",
    g_emoji: "Emoji",
    // Login screens
    auth_clear_session: "Clear stored session",
    auth_code_expired: 'Code expired. Tap "Via Bot" again for a new link.',
    auth_widget_session_note: "Uses your <b>web.telegram.org</b> session. If you log in with the wrong account, sign out at web.telegram.org first.",
    auth_bot_steps: "1. Tap the blue button above<br>2. In Telegram, tap <b>Start</b> on the bot<br>3. Come back here — auto-logs in",
    auth_bot_not_configured: "Bot not configured",
    auth_connecting: "Connecting…",
    btn_retry: "Retry",
    set_theme_sub: "Tap to change",
    set_bottom_nav: "Bottom Navigation",
    nav_pick_hint: "Pick 3-5 features to show in the bottom nav. Tap a tile to add or remove. Number shows position.",
    nav_max_warning: "Max 5 tabs — remove one first",
    nav_min_warning: "Need at least 3 tabs",
    // What's New + Tips (v8.49.0)
    news_whatsnew: "What's New",
    news_got_it: "Got it",
    news_see_all: "See all",
    news_timeline_title: "Tips & News",
    set_about: "About",
    set_tips_news: "Tips & News",
    set_tips_news_sub: "What's new — release history",
    // Cooking (v8.48.0)
    ck_total_all: "Total cost of all dishes",
    ck_search_ph: "Search dishes...",
    ck_my_dishes: "My Dishes",
    ck_sort_by: "Sort by",
    ck_sort_recent: "Recent",
    ck_sort_name: "Name (A–Z)",
    ck_sort_cost_low: "Cheapest",
    ck_sort_cost_high: "Priciest",
    ck_fav_only: "Favorites only",
    ck_no_favs: "No favorite dishes yet. Tap the ♥ on a dish to add it here.",
    ck_no_dishes_t: "No dishes yet",
    ck_no_dishes_s: "Tap + to add your first recipe",
    ck_no_match: "No dishes match your search",
    ck_serving: "serving",
    ck_servings_short: "servings",
    ck_servings: "Servings",
    ck_total_cost: "Total cost",
    ck_cook_time: "Cook time",
    ck_cook_time_min: "Cook time (min)",
    ck_ingredients: "Ingredients",
    ck_prices_from: "Prices from shopping",
    ck_add_to_shop: "Add to Shopping List",
    ck_added_n_one: "Added {n} item to shopping",
    ck_added_n_other: "Added {n} items to shopping",
    ck_add_dish: "Add a Dish",
    ck_edit_dish: "Edit Dish",
    ck_dish_name: "Dish Name",
    ck_dish_name_ph: "e.g. Udon with Tempura",
    ck_description: "Description",
    ck_desc_ph: "Describe your dish...",
    ck_optional: "optional",
    ck_add_ingredient: "Add Ingredient",
    ck_no_ings: "No ingredients yet — tap below to add",
    ck_ing_name: "Name",
    ck_qty: "Qty",
    ck_unit: "Unit",
    ck_est_cost: "Estimated cost",
    ck_name_required: "Name required",
    ck_img_upload_failed: "Image upload failed",
    ck_delete_confirm: "Delete this dish?",
    ck_prices_updated_one: "Updated {n} price",
    ck_prices_updated_other: "Updated {n} prices",
    ck_prices_unchanged: "No prices changed",
    sh_in_stock: "In Stock",
    sh_bought: "Bought", sh_clear: "Clear", sh_edit_item: "Edit Item",
    mt_edit_sub: "Edit Subscription",
    mt_edit_zone_task: "Edit Cleaning Task",
    cl_reset_days: "Reset (days)",
    // Workout — active session (v8.35.0 polish)
    wx_reps: "Reps", wx_weight: "Weight", wx_add_set: "Add Set",
    wx_last_time: "Last time", wx_in_progress: "in progress",
    wx_completed: "Completed", wx_exercises: "exercises", wx_sets: "sets",
    wx_finish: "Finish Workout", wx_reopen: "Reopen workout",
    wx_delete_workout: "Delete workout", wx_delete_set_confirm: "Delete set?",
    wx_rest: "Rest", wx_skip: "Skip", wx_rest_done: "Rest complete!",
    sh_edit_folder: "Edit Folder", sh_folder_none: "None", sh_total: "Total",
    sh_delete_folder: "Delete Folder",
    // Money widgets / receipts
    m_balance_label: "Balance", m_monthly_total: "Monthly total",
    m_carried_over: "Carried over", m_this_month: "this month:",
    m_monthly: "Monthly", m_edit_tx: "Edit Transaction",
    m_item_name: "Item name", m_edit_receipt_item: "Edit Item",
    // Subtasks
    su_add_step: "Add step…", su_add: "Add",
    // Cleaning add task
    cl_add_task: "Add task…",
    // Trainings
    tr_create_template: "Create template", tr_empty_workout: "Empty workout",
    tr_add: "Add", tr_statistics: "Statistics",
    tr_no_template: "No template yet", tr_no_template_s: "Tap + to create one",
    // Plant edit modal
    pl_nickname: "Nickname", pl_species: "Species", pl_latin: "Latin name",
    pl_water_every_days: "Water every (days)", pl_light: "Light",
    pl_stage: "Growth stage", pl_stage_seed: "Seed", pl_stage_sprout: "Sprout", pl_stage_young: "Young", pl_stage_mature: "Mature",
    pl_notes_placeholder: "Personal reminders, anniversaries…",
    pl_nickname_placeholder: "e.g. Yuki",
    pl_loading: "Loading…", pl_snap_photo: "Snap a photo",
    pl_edit_details: "Edit details",
    // Recurring edit
    tk_edit_recur: "Edit Recurring", tk_status: "Status",
    tk_active: "Active", tk_paused: "Paused",
    // Misc
    g_no_words_t: "No words available", g_no_words_s: "Catalog is empty",
    g_no_matches: "No matches",
    g_undo: "Undo",
    g_quantity_hint: "e.g. 1kg", g_price_hint: "Price",
    // Income/Expense labels (long form for stat tiles)
    m_income_label: "Income", m_expense_label: "Expense",
  },

  ru: {
    nav_home: "Главная", nav_tasks: "Задачи", nav_words: "Слова", nav_money: "Финансы", nav_profile: "Профиль",
    nav_shop: "Покупки", nav_cooking: "Кухня", nav_life: "Жизнь", nav_trainings: "Зал", nav_plants: "Цветы", nav_birthdays: "ДР", nav_clean: "Уборка", nav_subs: "Подписки", nav_settings: "Настройки",
    // Life tab (v8.51.0)
    tt_life_t: "Жизнь", tt_life_s: "Твой живой баланс",
    life_you: "Ты", life_us: "Мы",
    life_hint_personal: "Тапни область чтобы растить · удержи фон для редактирования",
    life_hint_family: "Ваша связь — тапни область · удержи фон для редактирования",
    life_hint_area: "Тапни привычку · удержи пустое место чтобы добавить",
    life_hint_area_empty: "Удержи пустое место чтобы добавить привычку",
    life_new_habit: "Посадить привычку",
    life_habit: "Привычка",
    life_habit_name: "Название",
    life_habit_ph: "напр. Утренняя прогулка",
    life_type: "Тип",
    life_type_build: "Развивать", life_type_maintain: "Поддерживать", life_type_reduce: "Сокращать",
    life_frequency: "Как часто",
    life_daily: "Каждый день",
    life_streak: "Серия", life_consistency: "Стабильность",
    life_mark_done: "Отметить", life_done_today: "Сделано сегодня",
    life_name_required: "Дай ей название",
    life_delete_confirm: "Удалить привычку?",
    life_edit_node: "Изменить область", life_node_name: "Название", life_node_reset: "Сбросить к дефолту",
    life_ideas: "Идеи", life_ideas_sub: "Нажми + чтобы посадить любую",
    life_thinking: "Придумываю идеи для тебя…", life_no_ideas: "Не удалось получить идеи — попробуй ещё раз",
    life_edit_habit: "Изменить привычку",
    life_edit_on: "Редактирование — тапни узел чтобы изменить · тапни фон чтобы выйти",
    life_journey: "Путь", life_balance: "Баланс", life_connection: "Связь",
    life_j_activity: "Активность · 30 дней", life_j_habits: "Привычек", life_j_done_today: "Сегодня",
    life_j_this_week: "За неделю", life_j_best_streak: "Лучшая серия",
    life_j_empty: "Посади пару привычек, чтобы увидеть свой путь",
    life_challenges: "Вызовы", life_ch_current: "Текущие", life_ch_completed: "Готово",
    life_ch_new: "Новый", life_ch_goal: "Цель", life_ch_kind_count: "Счёт", life_ch_kind_streak: "Серия",
    life_ch_kind_score: "Счёт", life_ch_until: "До…", life_ch_ended: "Завершён",
    life_ch_target: "Цель", life_ch_times: "раз", life_ch_days_row: "дней подряд",
    life_ch_track: "Отслеживать", life_ch_anything: "Что угодно", life_ch_spheres: "Сферы", life_ch_habits: "Привычки",
    life_ch_period: "Период", life_ch_days: "дн.", life_ch_create: "Создать вызов",
    life_ch_title_ph: "напр. 5 тренировок за неделю", life_ch_done: "Готово", life_ch_failed: "Не вышло",
    life_ch_days_left_one: "{n} день", life_ch_days_left_few: "{n} дня", life_ch_days_left_many: "{n} дней", life_ch_days_left_other: "{n} дней",
    // Love Points
    love_title: "Очки любви", love_stats: "Статистика", love_stats_title: "Очки любви · этот месяц",
    love_days_left_one: "{n} день до конца месяца", love_days_left_few: "{n} дня до конца месяца", love_days_left_many: "{n} дней до конца месяца", love_days_left_other: "{n} дней до конца месяца",
    love_award_to: "Очко для %s", love_reason_ph: "За что?", love_give: "Дать очко",
    love_from: "от %s", love_a_point: "очко", love_no_points: "В этом месяце пока пусто — будь первым 💞",
    just_now: "только что", m_ago: " мин", h_ago: " ч",
    life_ch_empty_current: "Нет активных вызовов — создай ✨",
    life_ch_empty_completed: "Пока ничего не завершено",
    life_ch_delete_confirm: "Удалить вызов?",
    life_ch_participants: "Участники", life_ch_participants_hint: "Кто участвует — у каждого свой счёт. Живёт в Семье.",
    life_new_sphere: "Новая сфера", life_add_sphere: "Добавить сферу", life_sphere_ph: "напр. Путешествия",
    life_color: "Цвет", life_delete_sphere: "Удалить сферу",
    life_delete_sphere_confirm: "Удалить сферу и все её привычки?",
    tt_home_t: "Family HQ", tt_home_s: "Всё в одном месте",
    tt_tasks_t: "Задачи", tt_tasks_s: "Управление и назначение",
    tt_shop_t: "Покупки", tt_shop_s: "Общий список",
    tt_trainings_t: "Тренировки", tt_trainings_s: "Сессии и прогресс",
    tt_words_t: "Слова", tt_words_s: "Изучение лексики",
    tt_plants_t: "Растения", tt_plants_s: "Уход и полив",
    tt_cooking_t: "Кухня", tt_cooking_s: "Блюда и стоимость продуктов",
    tt_money_t: "Финансы", tt_money_s: "Бюджет и подписки",
    tt_profile_t: "Профиль", tt_profile_s: "Личная статистика",
    tt_events_t: "События", tt_events_s: "Расписание",
    tt_birthdays_t: "Дни рождения", tt_birthdays_s: "Не забудь",
    tt_clean_t: "Уборка", tt_clean_s: "Зоны квартиры",
    tt_settings_t: "Настройки", tt_settings_s: "Кастомизация",
    tt_subs_t: "Подписки", tt_subs_s: "Ежемесячные платежи",
    tt_recurring_t: "Повторяющиеся", tt_recurring_s: "Повторяющиеся задачи",
    btn_add: "Добавить", btn_save: "Сохранить", btn_cancel: "Отмена", btn_delete: "Удалить",
    btn_edit: "Изменить", btn_close: "Закрыть", btn_done: "Готово", btn_ok: "OK", btn_yes: "Да", btn_no: "Нет",
    btn_back: "Назад", btn_next: "Далее", btn_share: "Поделиться",
    btn_create: "Создать", btn_update: "Обновить", btn_join: "Войти",
    btn_remove: "Убрать", btn_set: "Задать", btn_start: "Начать",
    btn_finish: "Завершить", btn_apply: "Применить", btn_reset: "Сбросить",
    btn_take_photo: "Сделать фото", btn_choose_photo: "Выбрать фото",
    set_family: "Семья", set_members: "Участники", set_appearance: "Оформление",
    set_theme: "Тема", set_language: "Язык", set_notifications: "Уведомления",
    set_developer: "Разработчик", set_invite_code: "Код приглашения",
    set_share_invite: "Поделиться приглашением", set_leave_family: "Покинуть семью",
    set_share_hint: "Отправь этот код новым участникам",
    set_money: "Финансы", set_categories: "Категории", set_learning: "Обучение",
    set_integrations: "Интеграции", set_learning_lang: "Язык изучения",
    set_words_editor: "Редактор слов", set_reset_progress: "Сбросить мой прогресс",
    set_morning_digest: "Утренняя сводка", set_morning_digest_sub: "Разделы и порядок",
    set_trello_sync: "Trello",
    set_debug: "Режим отладки", set_words_editor_sub: "Карточки · картинки",
    set_reset_progress_sub: "Очистить мои выученные слова",
    g_loading: "Загрузка…", g_today: "Сегодня", g_yesterday: "Вчера", g_tomorrow: "Завтра",
    g_upcoming: "Скоро", g_completed: "Выполнено", g_all: "Все",
    g_active: "Активные", g_recurring: "Повторяющиеся", g_events: "События",
    g_calendar: "Календарь", g_upcoming_7: "Ближайшие 7 дней",
    g_tasks: "Задачи", g_subscriptions: "Подписки", g_birthdays: "Дни рождения",
    g_feels: "ощущ.", g_today_bday: "Сегодня! 🎉", g_no_items: "Пока пусто",
    g_by_category: "По категориям", g_limits: "Лимиты", g_menu: "Меню",
    g_morning: "Утро", g_afternoon: "День", g_evening: "Вечер",
    g_enter_code: "Введи 6-значный код",
    g_reminders: "Напоминания", g_date_of_birth: "Дата рождения",
    g_assigned_to: "Назначено", g_assign_to: "Назначить",
    g_start: "Начало", g_time: "Время", g_end_opt: "Конец (опционально)",
    g_schedule: "Расписание", g_daily: "Ежедневно", g_weekly: "Еженедельно", g_monthly: "Ежемесячно",
    g_days: "Дни", g_day_of_month: "День месяца", g_what_to_do: "Что нужно сделать?",
    g_due_date: "Срок", g_who: "Кто",
    g_every_day: "Каждый день", g_paused: "На паузе", g_done: "Готово", g_filter_all: "Все",
    // Pluralized — Russian needs one/few/many. trn() picks via Intl.PluralRules.
    g_in_days_short_one: "через {n} д.", g_in_days_short_few: "через {n} д.",
    g_in_days_short_many: "через {n} д.", g_in_days_short_other: "через {n} д.",
    g_in_days_full_one: "через {n} день",      // 1, 21, 31, 41...
    g_in_days_full_few: "через {n} дня",        // 2-4, 22-24, 32-34...
    g_in_days_full_many: "через {n} дней",      // 5-20, 25-30, 35-40...
    g_in_days_full_other: "через {n} дн",       // fallback (fractional)
    m_transactions: "Транзакции", m_analytics: "Аналитика",
    m_income: "Доход", m_expense: "Расход", m_balance: "Баланс",
    m_this_month: "Этот месяц",
    pl_thirsty: "Хочет пить", pl_soon: "Скоро полить", pl_healthy: "Здорово",
    pl_water: "Полить", pl_thanks: "Спасибо!", pl_add: "Добавить",
    pl_care_for: "Уход за", pl_water_every: "Поливать каждые",
    pl_growth_timeline: "История роста", pl_care_tips: "Советы по уходу",
    pl_update: "Проверить", pl_analyzing: "Анализирую фото…",
    pl_take_photo: "Сделать фото", pl_take_photo_d: "Сейчас, через камеру",
    pl_from_gallery: "Из галереи", pl_from_gallery_d: "Выбрать существующее",
    pl_camera_unavail: "Камера недоступна",
    pl_h_title: "Проверка состояния",
    pl_h_healthy: "Выглядит здоровым", pl_h_concern: "Нужно внимание", pl_h_critical: "Критично",
    pl_h_issues: "Что я вижу", pl_h_advice: "Что делать",
    pl_h_no_issues: "Проблем не вижу — продолжай в том же духе.",
    pl_h_view: "Посмотреть прошлую проверку",
    mt_add_task: "Новая задача", mt_edit_task: "Изменить задачу",
    mt_add_event: "Новое событие", mt_edit_event: "Изменить событие",
    mt_add_expense: "Расход", mt_add_income: "Доход",
    mt_add_shop: "Новый товар", mt_add_sub: "Новая подписка",
    mt_add_bday: "Новый день рождения", mt_add_recur: "Повторяющаяся задача",
    mt_add_plant: "Новое растение", mt_edit_plant: "Изменить растение",
    mt_more: "Ещё", mt_photo: "Фото", mt_which_one: "Какое именно?",
    mt_create_family: "Создать семью", mt_join_family: "Присоединиться",
    mt_new_folder: "Новая папка", mt_categories: "Категории",
    mt_choose_city: "Выбрать город", mt_stats: "Статистика",
    mt_morning_digest: "Утренняя сводка", mt_learning_lang: "Язык изучения",
    mt_words: "Слова", mt_edit_word: "Изменить слово",
    mt_start_workout: "Начать тренировку", mt_new_template: "Новый шаблон",
    mt_edit_template: "Изменить шаблон", mt_edit_set: "Изменить подход",
    mt_edit_workout: "Изменить тренировку", mt_add_exercise: "Добавить упражнение",
    mt_progress: "Прогресс", mt_edit_bday: "Изменить день рождения", mt_add_zone: "Новая зона",
    mt_choose_theme: "Выбрать тему", mt_custom_theme: "Своя тема",
    mt_new_cat: "Новая категория", mt_edit_cat: "Изменить категорию",
    mt_new_exercise: "Новое упражнение", mt_workout: "Тренировка",
    f_title: "Название", f_text: "Текст", f_amount: "Сумма", f_currency: "Валюта",
    f_category: "Категория", f_description: "Описание", f_date: "Дата",
    f_priority: "Приоритет", f_assigned_to: "Назначено", f_when: "Когда",
    f_repeat: "Повтор", f_emoji: "Эмодзи", f_name: "Имя", f_quantity: "Количество",
    f_price: "Цена", f_folder: "Папка", f_notes: "Заметки", f_color: "Цвет",
    f_image: "Картинка", f_caption: "Подпись",
    p_low: "Низкий", p_normal: "Обычный", p_high: "Высокий",
    cf_delete_task: "Удалить задачу?", cf_delete_event: "Удалить событие?",
    cf_delete_transaction: "Удалить транзакцию?",
    cf_delete_generic: "Удалить?", cf_leave_family: "Покинуть семью?",
    tk_overdue: "Просрочено", tk_high_pri: "Высокий приоритет", tk_this_week: "На этой неделе",
    tk_rest: "Остальные", tk_caught_up: "Всё под контролем! 🎉",
    tk_no_recur_t: "Нет повторяющихся задач", tk_no_recur_s: "Нажми + чтобы создать",
    ts_saved: "Сохранено", ts_deleted: "Удалено", ts_error: "Ошибка",
    ts_network: "Ошибка сети", ts_copied: "Скопировано",
    ts_save_failed: "Не сохранилось", ts_upload_failed: "Загрузка не удалась",
    ts_upload_error: "Ошибка загрузки", ts_failed: "Ошибка",
    ts_image_saved: "Картинка сохранена", ts_image_removed: "Картинка удалена",
    ts_photo_added: "Фото добавлено", ts_photo_deleted: "Фото удалено",
    ts_caption_saved: "Подпись сохранена", ts_too_large: "Слишком большой (>15 МБ)",
    ts_word_required: "Слово нужно с обеих сторон",
    ts_watering_undone: "↩ Полив отменён",
    es_no_tasks_t: "Задач пока нет", es_no_tasks_s: "Нажми + чтобы добавить",
    es_no_events_t: "Событий нет", es_no_events_s: "Нажми + чтобы добавить",
    es_no_birthdays_t: "Дней рождения нет", es_no_birthdays_s: "Добавь ниже",
    es_no_subs_t: "Подписок нет", es_no_subs_s: "Добавь ниже",
    es_no_zones_t: "Зон пока нет", es_no_zones_s: "Добавь ниже",
    es_no_txs_t: "Транзакций нет", es_no_txs_s: "Нажми + чтобы добавить",
    es_no_shop_t: "Список пуст", es_no_shop_s: "Нажми + чтобы добавить",
    es_no_stock_t: "Запасов нет", es_no_stock_s: "Покупки появятся здесь",
    es_no_match_t: "Ничего не найдено", es_no_match_s: "Попробуй другой запрос",
    dow_short_sun: "Вс", dow_short_mon: "Пн", dow_short_tue: "Вт", dow_short_wed: "Ср",
    dow_short_thu: "Чт", dow_short_fri: "Пт", dow_short_sat: "Сб",
    dow_full_sun: "Воскресенье", dow_full_mon: "Понедельник", dow_full_tue: "Вторник", dow_full_wed: "Среда",
    dow_full_thu: "Четверг", dow_full_fri: "Пятница", dow_full_sat: "Суббота",
    mo_full_1: "Январь", mo_full_2: "Февраль", mo_full_3: "Март", mo_full_4: "Апрель",
    mo_full_5: "Май", mo_full_6: "Июнь", mo_full_7: "Июль", mo_full_8: "Август",
    mo_full_9: "Сентябрь", mo_full_10: "Октябрь", mo_full_11: "Ноябрь", mo_full_12: "Декабрь",
    mo_short_1: "Янв", mo_short_2: "Фев", mo_short_3: "Мар", mo_short_4: "Апр",
    mo_short_5: "Май", mo_short_6: "Июн", mo_short_7: "Июл", mo_short_8: "Авг",
    mo_short_9: "Сен", mo_short_10: "Окт", mo_short_11: "Ноя", mo_short_12: "Дек",
    th_midnight: "Полночь", th_dawn: "Рассвет", th_forest: "Лес", th_ocean: "Океан",
    th_rose: "Роза", th_chalk: "Мел", th_onyx: "Оникс", th_lavender: "Лаванда",
    th_sunset: "Закат", th_custom: "Своя",
    wd_session_complete: "Сессия завершена!",
    wd_next_session: "Следующая сессия",
    wd_correct_of: "{n} из {total} правильно",
    wd_dont_know: "Не знаю",
    wd_check: "Проверить",
    wd_no_learned_t: "Выученных слов пока нет",
    wd_no_learned_s: "Продолжай практику",
    wd_no_mistakes_t: "Ошибок нет",
    wd_no_mistakes_s: "Отлично!",
    wd_now_learning_en: "Учим английский",
    wd_now_learning_ru: "Учим русский",
    wd_reset_confirm: "Сбросить весь прогресс Words для {lang}?\n\nЭто очистит выученные/изучаемые слова для текущего языка. Другие участники семьи не пострадают.",
    wd_load_failed: "Не удалось загрузить.",
    wd_english: "Английский", wd_russian: "Русский",
    pl_no_plants_t: "Растений пока нет",
    pl_no_plants_s: "Нажми + Добавить и сфоткай — AI определит вид",
    pl_pick_photo: "Сделай фото или выбери из галереи",
    pl_tap_to_change: "Нажми чтобы изменить",
    pl_add_photo_short: "Добавить фото",
    pl_replace_photo: "Заменить фото",
    pl_delete_plant: "Удалить растение",
    pl_delete_photo_confirm: "Удалить это фото?",
    pl_delete_plant_confirm: "Удалить {name}? Это нельзя отменить.",
    pl_no_waterings_window: "В этом окне поливов не было",
    pl_days_unit: "дней",
    pl_caption: "Подпись",
    wx_no_location: "Без локации",
    wx_set_city: "Укажи город чтобы увидеть прогноз",
    wx_choose_city: "Выбрать город",
    wx_no_forecast: "Прогноз недоступен",
    wx_no_results: "Ничего не найдено",
    g_close: "Закрыть", g_remove_image_confirm: "Убрать картинку?",
    g_emoji: "Эмодзи",
    auth_clear_session: "Очистить сессию",
    auth_code_expired: 'Код истёк. Нажми "Через бота" чтобы получить новый.',
    auth_widget_session_note: "Использует твою сессию <b>web.telegram.org</b>. Если ты вошёл не тем аккаунтом — сначала выйди на web.telegram.org.",
    auth_bot_steps: "1. Нажми синюю кнопку выше<br>2. В Telegram нажми <b>Start</b> у бота<br>3. Вернись сюда — войдёт автоматически",
    auth_bot_not_configured: "Бот не настроен",
    auth_connecting: "Подключение…",
    btn_retry: "Повторить",
    set_theme_sub: "Нажми чтобы изменить",
    set_bottom_nav: "Нижнее меню",
    nav_pick_hint: "Выбери 3-5 вкладок для нижнего меню. Тап по плитке — добавить/убрать. Номер показывает позицию.",
    nav_max_warning: "Максимум 5 вкладок — убери одну",
    nav_min_warning: "Нужно минимум 3 вкладки",
    // What's New + Tips (v8.49.0)
    news_whatsnew: "Что нового",
    news_got_it: "Понятно",
    news_see_all: "Все обновления",
    news_timeline_title: "Советы и новости",
    set_about: "О приложении",
    set_tips_news: "Советы и новости",
    set_tips_news_sub: "Что нового — история обновлений",
    // Cooking (v8.48.0)
    ck_total_all: "Общая стоимость блюд",
    ck_search_ph: "Поиск блюд...",
    ck_my_dishes: "Мои блюда",
    ck_sort_by: "Сортировка",
    ck_sort_recent: "Новые",
    ck_sort_name: "По имени (А–Я)",
    ck_sort_cost_low: "Дешевле",
    ck_sort_cost_high: "Дороже",
    ck_fav_only: "Только избранные",
    ck_no_favs: "Пока нет избранных блюд. Нажми ♥ на блюде, чтобы добавить сюда.",
    ck_no_dishes_t: "Пока нет блюд",
    ck_no_dishes_s: "Нажми + чтобы добавить первое",
    ck_no_match: "Ничего не найдено",
    ck_serving: "порция",
    ck_servings_short: "порц.",
    ck_servings: "Порций",
    ck_total_cost: "Стоимость",
    ck_cook_time: "Время",
    ck_cook_time_min: "Время (мин)",
    ck_ingredients: "Ингредиенты",
    ck_prices_from: "Цены из покупок",
    ck_add_to_shop: "Добавить в список покупок",
    ck_added_n_one: "Добавлен {n} продукт в покупки",
    ck_added_n_few: "Добавлено {n} продукта в покупки",
    ck_added_n_many: "Добавлено {n} продуктов в покупки",
    ck_added_n_other: "Добавлено {n} продуктов в покупки",
    ck_add_dish: "Добавить блюдо",
    ck_edit_dish: "Изменить блюдо",
    ck_dish_name: "Название блюда",
    ck_dish_name_ph: "напр. Удон с темпурой",
    ck_description: "Описание",
    ck_desc_ph: "Опиши блюдо...",
    ck_optional: "необязательно",
    ck_add_ingredient: "Добавить ингредиент",
    ck_no_ings: "Нет ингредиентов — нажми ниже чтобы добавить",
    ck_ing_name: "Название",
    ck_qty: "Кол-во",
    ck_unit: "Ед.",
    ck_est_cost: "Примерная стоимость",
    ck_name_required: "Укажи название",
    ck_img_upload_failed: "Не удалось загрузить фото",
    ck_delete_confirm: "Удалить блюдо?",
    ck_prices_updated_one: "Обновлена {n} цена",
    ck_prices_updated_few: "Обновлено {n} цены",
    ck_prices_updated_many: "Обновлено {n} цен",
    ck_prices_updated_other: "Обновлено {n} цен",
    ck_prices_unchanged: "Цены не изменились",
    sh_in_stock: "В наличии",
    sh_bought: "Куплено", sh_clear: "Очистить", sh_edit_item: "Изменить товар",
    mt_edit_sub: "Изменить подписку",
    mt_edit_zone_task: "Изменить задачу зоны",
    cl_reset_days: "Сброс (дней)",
    wx_reps: "Повторы", wx_weight: "Вес", wx_add_set: "Добавить подход",
    wx_last_time: "В прошлый раз", wx_in_progress: "в процессе",
    wx_completed: "Завершено", wx_exercises: "упр.", wx_sets: "подх.",
    wx_finish: "Завершить тренировку", wx_reopen: "Открыть заново",
    wx_delete_workout: "Удалить тренировку", wx_delete_set_confirm: "Удалить подход?",
    wx_rest: "Отдых", wx_skip: "Пропустить", wx_rest_done: "Отдых завершён!",
    sh_edit_folder: "Изменить папку", sh_folder_none: "Без папки", sh_total: "Итого",
    sh_delete_folder: "Удалить папку",
    m_balance_label: "Баланс", m_monthly_total: "В месяц",
    m_carried_over: "Перенос", m_this_month: "в этом месяце:",
    m_monthly: "По месяцам", m_edit_tx: "Изменить транзакцию",
    m_item_name: "Название", m_edit_receipt_item: "Изменить позицию",
    su_add_step: "Добавить шаг…", su_add: "Добавить",
    cl_add_task: "Добавить задачу…",
    tr_create_template: "Создать шаблон", tr_empty_workout: "Пустая тренировка",
    tr_add: "Добавить", tr_statistics: "Статистика",
    tr_no_template: "Шаблонов пока нет", tr_no_template_s: "Нажми + чтобы создать",
    pl_nickname: "Имя", pl_species: "Вид", pl_latin: "Латинское название",
    pl_water_every_days: "Поливать каждые (дней)", pl_light: "Свет",
    pl_stage: "Стадия роста", pl_stage_seed: "Семя", pl_stage_sprout: "Росток", pl_stage_young: "Молодое", pl_stage_mature: "Взрослое",
    pl_notes_placeholder: "Личные напоминания, события…",
    pl_nickname_placeholder: "напр. Юки",
    pl_loading: "Загрузка…", pl_snap_photo: "Сфотографируй",
    pl_edit_details: "Изменить детали",
    tk_edit_recur: "Изменить повтор", tk_status: "Статус",
    tk_active: "Активна", tk_paused: "На паузе",
    g_no_words_t: "Слов нет", g_no_words_s: "Каталог пуст",
    g_no_matches: "Ничего не найдено",
    g_undo: "Отменить",
    g_quantity_hint: "напр. 1кг", g_price_hint: "Цена",
    m_income_label: "Доход", m_expense_label: "Расход",
  }
};
