# -*- coding: utf-8 -*-
"""
Word of the Day catalog — bilingual (Russian ↔ English) entries.
Rotated daily via `day_of_year % len(WORDS)`. Add more entries any time;
order doesn't matter (the deterministic rotation just cycles).

Format: each entry is a dict with simple definitions (B1–B2 level).
"""

WORDS = [
    # ─── Concepts / qualities ────────────────────────────────────────────
    {"ru_word": "Любопытство", "ru_def": "Желание узнать что-то новое или интересное.",
     "en_word": "Curiosity", "en_def": "A strong desire to learn or know something."},
    {"ru_word": "Решимость", "ru_def": "Твёрдая воля довести дело до конца.",
     "en_word": "Determination", "en_def": "A firm intention to keep doing something until it's finished."},
    {"ru_word": "Уязвимость", "ru_def": "Способность быть открытым к боли или критике.",
     "en_word": "Vulnerability", "en_def": "The willingness to be open to emotional risk or hurt."},
    {"ru_word": "Изобретательность", "ru_def": "Умение находить новые и умные решения.",
     "en_word": "Ingenuity", "en_def": "The ability to invent clever solutions to problems."},
    {"ru_word": "Подлинность", "ru_def": "Качество быть настоящим, не поддельным.",
     "en_word": "Authenticity", "en_def": "The quality of being real and genuine, not fake."},
    {"ru_word": "Стойкость", "ru_def": "Способность держаться и не ломаться в трудностях.",
     "en_word": "Resilience", "en_def": "The ability to recover quickly from difficulties."},
    {"ru_word": "Великодушие", "ru_def": "Готовность давать больше, чем требуется.",
     "en_word": "Generosity", "en_def": "Readiness to give more of something than is necessary or expected."},
    {"ru_word": "Сосредоточенность", "ru_def": "Полное внимание к одному делу.",
     "en_word": "Focus", "en_def": "The state of paying close attention to one thing."},
    {"ru_word": "Осознанность", "ru_def": "Внимание к тому, что происходит здесь и сейчас.",
     "en_word": "Mindfulness", "en_def": "Being fully aware of the present moment."},
    {"ru_word": "Терпение", "ru_def": "Способность спокойно ждать или переносить трудности.",
     "en_word": "Patience", "en_def": "The ability to wait or endure without getting upset."},

    {"ru_word": "Признательность", "ru_def": "Чувство благодарности за то, что у тебя есть.",
     "en_word": "Gratitude", "en_def": "The feeling of being thankful for what you have."},
    {"ru_word": "Намерение", "ru_def": "Чёткое желание что-то сделать.",
     "en_word": "Intention", "en_def": "A clear plan or aim to do something."},
    {"ru_word": "Привычка", "ru_def": "Действие, которое повторяется почти автоматически.",
     "en_word": "Habit", "en_def": "A behaviour you do regularly, often without thinking."},
    {"ru_word": "Возможность", "ru_def": "Шанс, который можно использовать.",
     "en_word": "Opportunity", "en_def": "A favourable chance to do something."},
    {"ru_word": "Препятствие", "ru_def": "То, что мешает двигаться вперёд.",
     "en_word": "Obstacle", "en_def": "Something that blocks your progress."},
    {"ru_word": "Озарение", "ru_def": "Внезапное понимание чего-то важного.",
     "en_word": "Insight", "en_def": "A sudden, deep understanding of something."},
    {"ru_word": "Сожаление", "ru_def": "Грусть о том, что сделано или упущено.",
     "en_word": "Regret", "en_def": "Sadness about something that has happened or been missed."},
    {"ru_word": "Облегчение", "ru_def": "Чувство, когда трудность прошла.",
     "en_word": "Relief", "en_def": "A feeling of comfort when a worry or problem ends."},
    {"ru_word": "Сомнение", "ru_def": "Неуверенность, верно ли что-то.",
     "en_word": "Doubt", "en_def": "A feeling of being unsure about something."},
    {"ru_word": "Восхищение", "ru_def": "Сильное уважение и удивление.",
     "en_word": "Admiration", "en_def": "Strong respect mixed with warmth or wonder."},

    {"ru_word": "Удивление", "ru_def": "Реакция на что-то неожиданное.",
     "en_word": "Astonishment", "en_def": "A feeling of great surprise."},
    {"ru_word": "Скромность", "ru_def": "Не выставлять напоказ свои достоинства.",
     "en_word": "Modesty", "en_def": "Not showing off your abilities or success."},
    {"ru_word": "Снисхождение", "ru_def": "Мягкое, прощающее отношение.",
     "en_word": "Leniency", "en_def": "Being kind and forgiving when judging others."},
    {"ru_word": "Сочувствие", "ru_def": "Способность понимать чужую боль.",
     "en_word": "Compassion", "en_def": "Caring about the suffering of others and wanting to help."},
    {"ru_word": "Откровенность", "ru_def": "Честность в словах и чувствах.",
     "en_word": "Candor", "en_def": "Honesty and directness when speaking."},
    {"ru_word": "Скептицизм", "ru_def": "Привычка сомневаться, пока не появятся доказательства.",
     "en_word": "Skepticism", "en_def": "A doubting attitude that asks for proof."},
    {"ru_word": "Восторг", "ru_def": "Очень сильная радость.",
     "en_word": "Delight", "en_def": "A feeling of great pleasure."},
    {"ru_word": "Беспокойство", "ru_def": "Лёгкое чувство тревоги.",
     "en_word": "Concern", "en_def": "A feeling of worry."},
    {"ru_word": "Усталость", "ru_def": "Состояние, когда нужны отдых и сон.",
     "en_word": "Fatigue", "en_def": "Extreme tiredness from work or strain."},
    {"ru_word": "Вдохновение", "ru_def": "Прилив идей и желания творить.",
     "en_word": "Inspiration", "en_def": "A sudden idea or urge to create."},

    # ─── Verbs ──────────────────────────────────────────────────────────
    {"ru_word": "Размышлять", "ru_def": "Думать о чём-то медленно и глубоко.",
     "en_word": "Ponder", "en_def": "To think about something carefully for a long time."},
    {"ru_word": "Задерживаться", "ru_def": "Оставаться где-то дольше обычного.",
     "en_word": "Linger", "en_def": "To stay in a place longer than necessary."},
    {"ru_word": "Стремиться", "ru_def": "Сильно хотеть достичь цели.",
     "en_word": "Strive", "en_def": "To try very hard to achieve something."},
    {"ru_word": "Уговаривать", "ru_def": "Мягко убеждать кого-то.",
     "en_word": "Coax", "en_def": "To persuade someone gently."},
    {"ru_word": "Замечать", "ru_def": "Видеть то, что другие могут упустить.",
     "en_word": "Notice", "en_def": "To see or become aware of something."},
    {"ru_word": "Признавать", "ru_def": "Соглашаться, что что-то правда.",
     "en_word": "Acknowledge", "en_def": "To accept or admit that something is true."},
    {"ru_word": "Откладывать", "ru_def": "Переносить дело на потом.",
     "en_word": "Postpone", "en_def": "To move something to a later time."},
    {"ru_word": "Сосредоточиться", "ru_def": "Направить все мысли на одно.",
     "en_word": "Concentrate", "en_def": "To focus all your attention on one thing."},
    {"ru_word": "Колебаться", "ru_def": "Не решаться сделать выбор.",
     "en_word": "Hesitate", "en_def": "To pause before doing or saying something."},
    {"ru_word": "Завершить", "ru_def": "Довести дело до конца.",
     "en_word": "Accomplish", "en_def": "To finish or achieve something successfully."},

    {"ru_word": "Совершенствовать", "ru_def": "Делать что-то всё лучше.",
     "en_word": "Refine", "en_def": "To improve something by making small changes."},
    {"ru_word": "Превосходить", "ru_def": "Быть лучше других.",
     "en_word": "Excel", "en_def": "To be very good at something."},
    {"ru_word": "Ободрять", "ru_def": "Поддерживать словом или жестом.",
     "en_word": "Encourage", "en_def": "To give someone confidence to do something."},
    {"ru_word": "Подразумевать", "ru_def": "Иметь в виду, не говоря прямо.",
     "en_word": "Imply", "en_def": "To suggest something indirectly."},
    {"ru_word": "Затрагивать", "ru_def": "Касаться какой-то темы или чувства.",
     "en_word": "Touch on", "en_def": "To briefly mention a subject."},
    {"ru_word": "Раскрывать", "ru_def": "Делать что-то скрытое явным.",
     "en_word": "Unveil", "en_def": "To make something previously hidden public."},
    {"ru_word": "Утверждать", "ru_def": "Уверенно говорить, что что-то правда.",
     "en_word": "Assert", "en_def": "To say firmly that something is true."},
    {"ru_word": "Опровергнуть", "ru_def": "Доказать, что что-то неверно.",
     "en_word": "Refute", "en_def": "To prove that something is wrong."},
    {"ru_word": "Усваивать", "ru_def": "Понимать и запоминать новое.",
     "en_word": "Absorb", "en_def": "To learn or take in information."},
    {"ru_word": "Растягивать", "ru_def": "Делать длиннее во времени или пространстве.",
     "en_word": "Stretch", "en_def": "To extend something in length or duration."},

    # ─── Adjectives ─────────────────────────────────────────────────────
    {"ru_word": "Искренний", "ru_def": "Тот, кто говорит и чувствует по-настоящему.",
     "en_word": "Sincere", "en_def": "Honest and truthful in feelings."},
    {"ru_word": "Глубокий", "ru_def": "Не поверхностный, имеющий смысл.",
     "en_word": "Profound", "en_def": "Showing great depth of meaning or feeling."},
    {"ru_word": "Обыденный", "ru_def": "Обычный, не выдающийся.",
     "en_word": "Mundane", "en_def": "Ordinary, lacking excitement."},
    {"ru_word": "Хрупкий", "ru_def": "Легко ломается или разрушается.",
     "en_word": "Fragile", "en_def": "Easily broken or damaged."},
    {"ru_word": "Изысканный", "ru_def": "Тонкий и красивый по вкусу.",
     "en_word": "Exquisite", "en_def": "Extremely beautiful or delicate."},
    {"ru_word": "Скромный", "ru_def": "Без лишней гордости.",
     "en_word": "Humble", "en_def": "Modest, not arrogant."},
    {"ru_word": "Щедрый", "ru_def": "Готовый легко делиться.",
     "en_word": "Generous", "en_def": "Willing to give freely."},
    {"ru_word": "Бесстрашный", "ru_def": "Тот, кто не боится трудностей.",
     "en_word": "Fearless", "en_def": "Without fear; brave."},
    {"ru_word": "Внимательный", "ru_def": "Замечает детали и заботится.",
     "en_word": "Attentive", "en_def": "Paying close attention; thoughtful."},
    {"ru_word": "Спокойный", "ru_def": "Не нервничает, уверенный.",
     "en_word": "Composed", "en_def": "Calm and in control of yourself."},

    {"ru_word": "Изобретательный", "ru_def": "Придумывает нестандартные решения.",
     "en_word": "Resourceful", "en_def": "Good at finding clever ways to solve problems."},
    {"ru_word": "Энергичный", "ru_def": "Полный сил и движения.",
     "en_word": "Vigorous", "en_def": "Full of energy and strength."},
    {"ru_word": "Любознательный", "ru_def": "Любящий узнавать новое.",
     "en_word": "Inquisitive", "en_def": "Eager to learn or know."},
    {"ru_word": "Великолепный", "ru_def": "Очень красивый, впечатляющий.",
     "en_word": "Magnificent", "en_def": "Extremely impressive or beautiful."},
    {"ru_word": "Тонкий", "ru_def": "Едва заметный, но важный.",
     "en_word": "Subtle", "en_def": "Slight and not obvious."},
    {"ru_word": "Очевидный", "ru_def": "Ясный и понятный сразу.",
     "en_word": "Evident", "en_def": "Easy to see or understand."},
    {"ru_word": "Двусмысленный", "ru_def": "Может пониматься по-разному.",
     "en_word": "Ambiguous", "en_def": "Having more than one possible meaning."},
    {"ru_word": "Безмятежный", "ru_def": "Глубоко спокойный и мирный.",
     "en_word": "Serene", "en_def": "Calm, peaceful, and untroubled."},
    {"ru_word": "Уютный", "ru_def": "Дающий ощущение тепла и удобства.",
     "en_word": "Cozy", "en_def": "Giving a feeling of warmth and comfort."},
    {"ru_word": "Праздничный", "ru_def": "Радостный, как в особый день.",
     "en_word": "Festive", "en_def": "Cheerful and full of celebration."},

    # ─── Useful nouns ───────────────────────────────────────────────────
    {"ru_word": "Привязанность", "ru_def": "Тёплая связь с кем-то или чем-то.",
     "en_word": "Attachment", "en_def": "A strong feeling of affection or loyalty."},
    {"ru_word": "Усилие", "ru_def": "Энергия, потраченная на что-то.",
     "en_word": "Effort", "en_def": "Energy used to achieve something."},
    {"ru_word": "Уверенность", "ru_def": "Знание, что ты справишься.",
     "en_word": "Confidence", "en_def": "Belief in your own ability."},
    {"ru_word": "Гармония", "ru_def": "Согласие частей друг с другом.",
     "en_word": "Harmony", "en_def": "A pleasing arrangement of parts."},
    {"ru_word": "Гибкость", "ru_def": "Способность легко меняться.",
     "en_word": "Flexibility", "en_def": "The ability to adapt easily."},
    {"ru_word": "Ясность", "ru_def": "Когда всё понятно и просто.",
     "en_word": "Clarity", "en_def": "The quality of being clear and easy to understand."},
    {"ru_word": "Цельность", "ru_def": "Соответствие слов и дел.",
     "en_word": "Integrity", "en_def": "The quality of being honest and having strong morals."},
    {"ru_word": "Любознательность", "ru_def": "Тяга к знаниям.",
     "en_word": "Inquisitiveness", "en_def": "Eagerness to learn."},
    {"ru_word": "Восприятие", "ru_def": "Как ты видишь и понимаешь мир.",
     "en_word": "Perception", "en_def": "The way you understand or interpret something."},
    {"ru_word": "Ощущение", "ru_def": "То, что ты чувствуешь телом или душой.",
     "en_word": "Sensation", "en_def": "A physical or mental feeling."},

    {"ru_word": "Влечение", "ru_def": "Сильный интерес к человеку или делу.",
     "en_word": "Attraction", "en_def": "A strong pull towards someone or something."},
    {"ru_word": "Знакомство", "ru_def": "Первый контакт с чем-то новым.",
     "en_word": "Acquaintance", "en_def": "Slight knowledge of a person or thing."},
    {"ru_word": "Воспоминание", "ru_def": "Кусочек прошлого в памяти.",
     "en_word": "Memory", "en_def": "Something remembered from the past."},
    {"ru_word": "Тишина", "ru_def": "Отсутствие звуков и шума.",
     "en_word": "Silence", "en_def": "The absence of sound."},
    {"ru_word": "Граница", "ru_def": "Линия, за которую не переходят.",
     "en_word": "Boundary", "en_def": "A line that marks a limit."},
    {"ru_word": "Привычка", "ru_def": "Регулярное действие, которое стало автоматическим.",
     "en_word": "Routine", "en_def": "A regular way of doing things."},
    {"ru_word": "Назначение", "ru_def": "Цель, ради которой что-то существует.",
     "en_word": "Purpose", "en_def": "The reason for which something exists."},
    {"ru_word": "Преимущество", "ru_def": "То, что даёт тебе плюс.",
     "en_word": "Advantage", "en_def": "Something that gives you a better chance."},
    {"ru_word": "Недостаток", "ru_def": "Слабая или плохая сторона.",
     "en_word": "Drawback", "en_def": "A negative side of something."},
    {"ru_word": "Достижение", "ru_def": "Результат больших усилий.",
     "en_word": "Accomplishment", "en_def": "Something successfully completed."},

    {"ru_word": "Свобода", "ru_def": "Возможность выбирать без принуждения.",
     "en_word": "Freedom", "en_def": "The power to act or speak without restriction."},
    {"ru_word": "Ответственность", "ru_def": "Готовность отвечать за свои действия.",
     "en_word": "Responsibility", "en_def": "The duty to deal with something."},
    {"ru_word": "Слово", "ru_def": "Обещание, которое стоит сдержать.",
     "en_word": "Promise", "en_def": "A statement that you will do something."},
    {"ru_word": "Уважение", "ru_def": "Признание ценности человека.",
     "en_word": "Respect", "en_def": "A feeling of admiration for someone."},
    {"ru_word": "Доверие", "ru_def": "Вера в честность другого человека.",
     "en_word": "Trust", "en_def": "Firm belief in someone's reliability."},
    {"ru_word": "Соглашение", "ru_def": "Когда стороны договорились о чём-то.",
     "en_word": "Agreement", "en_def": "A decision shared by two or more people."},
    {"ru_word": "Препятствие", "ru_def": "Что-то, что мешает достичь цели.",
     "en_word": "Hindrance", "en_def": "Something that makes progress more difficult."},
    {"ru_word": "Успех", "ru_def": "Достижение того, чего хотел.",
     "en_word": "Success", "en_def": "Achieving what you set out to do."},
    {"ru_word": "Открытие", "ru_def": "Находка чего-то нового и важного.",
     "en_word": "Discovery", "en_def": "Finding something previously unknown."},
    {"ru_word": "Соревнование", "ru_def": "Борьба за лучший результат.",
     "en_word": "Competition", "en_def": "A contest to determine who is best."},

    # ─── Everyday / lifestyle ────────────────────────────────────────────
    {"ru_word": "Завтрак", "ru_def": "Утренний приём пищи.",
     "en_word": "Breakfast", "en_def": "The morning meal."},
    {"ru_word": "Прогулка", "ru_def": "Спокойная ходьба ради удовольствия.",
     "en_word": "Stroll", "en_def": "A relaxed walk."},
    {"ru_word": "Беседа", "ru_def": "Дружеский разговор без спешки.",
     "en_word": "Conversation", "en_def": "An informal exchange of thoughts."},
    {"ru_word": "Уют", "ru_def": "Чувство домашнего тепла и комфорта.",
     "en_word": "Coziness", "en_def": "A feeling of warm comfort at home."},
    {"ru_word": "Закат", "ru_def": "Момент, когда солнце уходит за горизонт.",
     "en_word": "Sunset", "en_def": "When the sun goes below the horizon."},
    {"ru_word": "Рассвет", "ru_def": "Время, когда солнце появляется.",
     "en_word": "Dawn", "en_def": "The first light of day."},
    {"ru_word": "Сумерки", "ru_def": "Полутёмное время между днём и ночью.",
     "en_word": "Twilight", "en_def": "The soft light just after sunset."},
    {"ru_word": "Прохлада", "ru_def": "Лёгкий приятный холод.",
     "en_word": "Coolness", "en_def": "A pleasant slight coldness."},
    {"ru_word": "Свежесть", "ru_def": "Чистота воздуха или новизна вкуса.",
     "en_word": "Freshness", "en_def": "The quality of being new, clean, or pure."},
    {"ru_word": "Аромат", "ru_def": "Приятный запах.",
     "en_word": "Aroma", "en_def": "A pleasant smell."},

    {"ru_word": "Намёк", "ru_def": "Неявный знак или подсказка.",
     "en_word": "Hint", "en_def": "An indirect suggestion."},
    {"ru_word": "Загадка", "ru_def": "То, что нужно разгадать.",
     "en_word": "Riddle", "en_def": "A puzzle phrased as a question."},
    {"ru_word": "Сюрприз", "ru_def": "Что-то неожиданное и приятное.",
     "en_word": "Surprise", "en_def": "An unexpected event."},
    {"ru_word": "Награда", "ru_def": "То, что получаешь за заслуги.",
     "en_word": "Reward", "en_def": "Something given for an achievement."},
    {"ru_word": "Поддержка", "ru_def": "Помощь словом или делом.",
     "en_word": "Support", "en_def": "Help or encouragement."},
    {"ru_word": "Привычка", "ru_def": "То, что делается каждый день автоматически.",
     "en_word": "Custom", "en_def": "A traditional way of behaving."},
    {"ru_word": "Долг", "ru_def": "То, что ты обязан сделать.",
     "en_word": "Duty", "en_def": "Something you must do."},
    {"ru_word": "Цель", "ru_def": "То, к чему ты стремишься.",
     "en_word": "Goal", "en_def": "Something you aim for."},
    {"ru_word": "Стремление", "ru_def": "Сильное желание добиться чего-то.",
     "en_word": "Aspiration", "en_def": "A strong hope or desire."},
    {"ru_word": "Талант", "ru_def": "Природная способность к делу.",
     "en_word": "Talent", "en_def": "A natural ability to do something well."},
]
