# -*- coding: utf-8 -*-
"""
Word of the Day catalog — bilingual (Russian ↔ English) entries.
Rotated daily via `day_of_year % len(WORDS)`. Add more entries any time;
order doesn't matter (the deterministic rotation just cycles).

Format: each entry is a dict with simple definitions (B1–B2 level).
"""

WORDS = [
    # ─── Concepts / qualities ────────────────────────────────────────────
    {"ru_word": "Любопы́тство", "ru_ipa": "[любапытства]",
     "ru_def": "Желание узнать что-то новое или интересное.",
     "en_word": "Curiosity", "en_ipa": "/ˌkjʊəriˈɒsɪti/",
     "en_def": "A strong desire to learn or know something."},
    {"ru_word": "Реши́мость", "ru_ipa": "[р'ишымаст']",
     "ru_def": "Твёрдая воля довести дело до конца.",
     "en_word": "Determination", "en_ipa": "/dɪˌtɜːmɪˈneɪʃən/",
     "en_def": "A firm intention to keep doing something until it's finished."},
    {"ru_word": "Уязви́мость", "ru_ipa": "[уйизв'имаст']",
     "ru_def": "Способность быть открытым к боли или критике.",
     "en_word": "Vulnerability", "en_ipa": "/ˌvʌlnərəˈbɪlɪti/",
     "en_def": "The willingness to be open to emotional risk or hurt."},
    {"ru_word": "Изобрета́тельность", "ru_ipa": "[изабр'итат'ил'наст']",
     "ru_def": "Умение находить новые и умные решения.",
     "en_word": "Ingenuity", "en_ipa": "/ˌɪndʒɪˈnjuːɪti/",
     "en_def": "The ability to invent clever solutions to problems."},
    {"ru_word": "По́длинность", "ru_ipa": "[подл'инаст']",
     "ru_def": "Качество быть настоящим, не поддельным.",
     "en_word": "Authenticity", "en_ipa": "/ˌɔːθenˈtɪsɪti/",
     "en_def": "The quality of being real and genuine, not fake."},
    {"ru_word": "Сто́йкость", "ru_ipa": "[стойкаст']",
     "ru_def": "Способность держаться и не ломаться в трудностях.",
     "en_word": "Resilience", "en_ipa": "/rɪˈzɪliəns/",
     "en_def": "The ability to recover quickly from difficulties."},
    {"ru_word": "Великоду́шие", "ru_ipa": "[в'ил'икадушыйэ]",
     "ru_def": "Готовность давать больше, чем требуется.",
     "en_word": "Generosity", "en_ipa": "/ˌdʒenəˈrɒsɪti/",
     "en_def": "Readiness to give more of something than is necessary or expected."},
    {"ru_word": "Сосредото́ченность", "ru_ipa": "[саср'идаточ'инаст']",
     "ru_def": "Полное внимание к одному делу.",
     "en_word": "Focus", "en_ipa": "/ˈfoʊkəs/",
     "en_def": "The state of paying close attention to one thing."},
    {"ru_word": "Осо́знанность", "ru_ipa": "[асознанаст']",
     "ru_def": "Внимание к тому, что происходит здесь и сейчас.",
     "en_word": "Mindfulness", "en_ipa": "/ˈmaɪndfəlnəs/",
     "en_def": "Being fully aware of the present moment."},
    {"ru_word": "Терпе́ние", "ru_ipa": "[т'ирп'эн'ийэ]",
     "ru_def": "Способность спокойно ждать или переносить трудности.",
     "en_word": "Patience", "en_ipa": "/ˈpeɪʃəns/",
     "en_def": "The ability to wait or endure without getting upset."},

    {"ru_word": "Призна́тельность", "ru_ipa": "[пр'изнат'ил'наст']",
     "ru_def": "Чувство благодарности за то, что у тебя есть.",
     "en_word": "Gratitude", "en_ipa": "/ˈɡrætɪtjuːd/",
     "en_def": "The feeling of being thankful for what you have."},
    {"ru_word": "Наме́рение", "ru_ipa": "[нам'эр'ин'ийэ]",
     "ru_def": "Чёткое желание что-то сделать.",
     "en_word": "Intention", "en_ipa": "/ɪnˈtenʃən/",
     "en_def": "A clear plan or aim to do something."},
    {"ru_word": "Привы́чка", "ru_ipa": "[пр'ивычка]",
     "ru_def": "Действие, которое повторяется почти автоматически.",
     "en_word": "Habit", "en_ipa": "/ˈhæbɪt/",
     "en_def": "A behaviour you do regularly, often without thinking."},
    {"ru_word": "Возмо́жность", "ru_ipa": "[вазможнаст']",
     "ru_def": "Шанс, который можно использовать.",
     "en_word": "Opportunity", "en_ipa": "/ˌɒpəˈtjuːnɪti/",
     "en_def": "A favourable chance to do something."},
    {"ru_word": "Препя́тствие", "ru_ipa": "[пр'ип'ацтв'ийэ]",
     "ru_def": "То, что мешает двигаться вперёд.",
     "en_word": "Obstacle", "en_ipa": "/ˈɒbstəkəl/",
     "en_def": "Something that blocks your progress."},
    {"ru_word": "Озаре́ние", "ru_ipa": "[азар'эн'ийэ]",
     "ru_def": "Внезапное понимание чего-то важного.",
     "en_word": "Insight", "en_ipa": "/ˈɪnsaɪt/",
     "en_def": "A sudden, deep understanding of something."},
    {"ru_word": "Сожале́ние", "ru_ipa": "[сажал'эн'ийэ]",
     "ru_def": "Грусть о том, что сделано или упущено.",
     "en_word": "Regret", "en_ipa": "/rɪˈɡret/",
     "en_def": "Sadness about something that has happened or been missed."},
    {"ru_word": "Облегче́ние", "ru_ipa": "[абл'икч'эн'ийэ]",
     "ru_def": "Чувство, когда трудность прошла.",
     "en_word": "Relief", "en_ipa": "/rɪˈliːf/",
     "en_def": "A feeling of comfort when a worry or problem ends."},
    {"ru_word": "Сомне́ние", "ru_ipa": "[самн'эн'ийэ]",
     "ru_def": "Неуверенность, верно ли что-то.",
     "en_word": "Doubt", "en_ipa": "/daʊt/",
     "en_def": "A feeling of being unsure about something."},
    {"ru_word": "Восхище́ние", "ru_ipa": "[васх'ищ'эн'ийэ]",
     "ru_def": "Сильное уважение и удивление.",
     "en_word": "Admiration", "en_ipa": "/ˌædməˈreɪʃən/",
     "en_def": "Strong respect mixed with warmth or wonder."},

    {"ru_word": "Удивле́ние", "ru_ipa": "[уд'ивл'эн'ийэ]",
     "ru_def": "Реакция на что-то неожиданное.",
     "en_word": "Astonishment", "en_ipa": "/əˈstɒnɪʃmənt/",
     "en_def": "A feeling of great surprise."},
    {"ru_word": "Скро́мность", "ru_ipa": "[скромнаст']",
     "ru_def": "Не выставлять напоказ свои достоинства.",
     "en_word": "Modesty", "en_ipa": "/ˈmɒdɪsti/",
     "en_def": "Not showing off your abilities or success."},
    {"ru_word": "Снисхожде́ние", "ru_ipa": "[сн'исхажд'эн'ийэ]",
     "ru_def": "Мягкое, прощающее отношение.",
     "en_word": "Leniency", "en_ipa": "/ˈliːniənsi/",
     "en_def": "Being kind and forgiving when judging others."},
    {"ru_word": "Сочу́вствие", "ru_ipa": "[сачуств'ийэ]",
     "ru_def": "Способность понимать чужую боль.",
     "en_word": "Compassion", "en_ipa": "/kəmˈpæʃən/",
     "en_def": "Caring about the suffering of others and wanting to help."},
    {"ru_word": "Открове́нность", "ru_ipa": "[аткрав'энаст']",
     "ru_def": "Честность в словах и чувствах.",
     "en_word": "Candor", "en_ipa": "/ˈkændər/",
     "en_def": "Honesty and directness when speaking."},
    {"ru_word": "Скептици́зм", "ru_ipa": "[скэпт'ицызм]",
     "ru_def": "Привычка сомневаться, пока не появятся доказательства.",
     "en_word": "Skepticism", "en_ipa": "/ˈskeptɪsɪzəm/",
     "en_def": "A doubting attitude that asks for proof."},
    {"ru_word": "Восто́рг", "ru_ipa": "[васторк]",
     "ru_def": "Очень сильная радость.",
     "en_word": "Delight", "en_ipa": "/dɪˈlaɪt/",
     "en_def": "A feeling of great pleasure."},
    {"ru_word": "Беспоко́йство", "ru_ipa": "[б'испакойства]",
     "ru_def": "Лёгкое чувство тревоги.",
     "en_word": "Concern", "en_ipa": "/kənˈsɜːn/",
     "en_def": "A feeling of worry."},
    {"ru_word": "Уста́лость", "ru_ipa": "[усталаст']",
     "ru_def": "Состояние, когда нужны отдых и сон.",
     "en_word": "Fatigue", "en_ipa": "/fəˈtiːɡ/",
     "en_def": "Extreme tiredness from work or strain."},
    {"ru_word": "Вдохнове́ние", "ru_ipa": "[вдахнав'эн'ийэ]",
     "ru_def": "Прилив идей и желания творить.",
     "en_word": "Inspiration", "en_ipa": "/ˌɪnspəˈreɪʃən/",
     "en_def": "A sudden idea or urge to create."},

    # ─── Verbs ──────────────────────────────────────────────────────────
    {"ru_word": "Размышля́ть", "ru_ipa": "[размышл'ат']",
     "ru_def": "Думать о чём-то медленно и глубоко.",
     "en_word": "Ponder", "en_ipa": "/ˈpɒndər/",
     "en_def": "To think about something carefully for a long time."},
    {"ru_word": "Заде́рживаться", "ru_ipa": "[зад'эржывацца]",
     "ru_def": "Оставаться где-то дольше обычного.",
     "en_word": "Linger", "en_ipa": "/ˈlɪŋɡər/",
     "en_def": "To stay in a place longer than necessary."},
    {"ru_word": "Стреми́ться", "ru_ipa": "[стр'им'ицца]",
     "ru_def": "Сильно хотеть достичь цели.",
     "en_word": "Strive", "en_ipa": "/straɪv/",
     "en_def": "To try very hard to achieve something."},
    {"ru_word": "Угова́ривать", "ru_ipa": "[угавар'иват']",
     "ru_def": "Мягко убеждать кого-то.",
     "en_word": "Coax", "en_ipa": "/koʊks/",
     "en_def": "To persuade someone gently."},
    {"ru_word": "Замеча́ть", "ru_ipa": "[зам'ич'ат']",
     "ru_def": "Видеть то, что другие могут упустить.",
     "en_word": "Notice", "en_ipa": "/ˈnoʊtɪs/",
     "en_def": "To see or become aware of something."},
    {"ru_word": "Признава́ть", "ru_ipa": "[пр'изнават']",
     "ru_def": "Соглашаться, что что-то правда.",
     "en_word": "Acknowledge", "en_ipa": "/əkˈnɒlɪdʒ/",
     "en_def": "To accept or admit that something is true."},
    {"ru_word": "Откла́дывать", "ru_ipa": "[аткладыват']",
     "ru_def": "Переносить дело на потом.",
     "en_word": "Postpone", "en_ipa": "/poʊstˈpoʊn/",
     "en_def": "To move something to a later time."},
    {"ru_word": "Сосредото́читься", "ru_ipa": "[саср'идаточ'ицца]",
     "ru_def": "Направить все мысли на одно.",
     "en_word": "Concentrate", "en_ipa": "/ˈkɒnsəntreɪt/",
     "en_def": "To focus all your attention on one thing."},
    {"ru_word": "Колеба́ться", "ru_ipa": "[кал'ибацца]",
     "ru_def": "Не решаться сделать выбор.",
     "en_word": "Hesitate", "en_ipa": "/ˈhezɪteɪt/",
     "en_def": "To pause before doing or saying something."},
    {"ru_word": "Заверши́ть", "ru_ipa": "[зав'иршыт']",
     "ru_def": "Довести дело до конца.",
     "en_word": "Accomplish", "en_ipa": "/əˈkʌmplɪʃ/",
     "en_def": "To finish or achieve something successfully."},

    {"ru_word": "Соверше́нствовать", "ru_ipa": "[сав'ирш'энствават']",
     "ru_def": "Делать что-то всё лучше.",
     "en_word": "Refine", "en_ipa": "/rɪˈfaɪn/",
     "en_def": "To improve something by making small changes."},
    {"ru_word": "Превосходи́ть", "ru_ipa": "[пр'ивасхад'ит']",
     "ru_def": "Быть лучше других.",
     "en_word": "Excel", "en_ipa": "/ɪkˈsel/",
     "en_def": "To be very good at something."},
    {"ru_word": "Ободря́ть", "ru_ipa": "[абадр'ат']",
     "ru_def": "Поддерживать словом или жестом.",
     "en_word": "Encourage", "en_ipa": "/ɪnˈkʌrɪdʒ/",
     "en_def": "To give someone confidence to do something."},
    {"ru_word": "Подразумева́ть", "ru_ipa": "[падразум'иват']",
     "ru_def": "Иметь в виду, не говоря прямо.",
     "en_word": "Imply", "en_ipa": "/ɪmˈplaɪ/",
     "en_def": "To suggest something indirectly."},
    {"ru_word": "Затра́гивать", "ru_ipa": "[затраг'иват']",
     "ru_def": "Касаться какой-то темы или чувства.",
     "en_word": "Touch on", "en_ipa": "/ˈtʌtʃ ɒn/",
     "en_def": "To briefly mention a subject."},
    {"ru_word": "Раскрыва́ть", "ru_ipa": "[раскрыват']",
     "ru_def": "Делать что-то скрытое явным.",
     "en_word": "Unveil", "en_ipa": "/ʌnˈveɪl/",
     "en_def": "To make something previously hidden public."},
    {"ru_word": "Утвержда́ть", "ru_ipa": "[утв'ирждат']",
     "ru_def": "Уверенно говорить, что что-то правда.",
     "en_word": "Assert", "en_ipa": "/əˈsɜːt/",
     "en_def": "To say firmly that something is true."},
    {"ru_word": "Опрове́ргнуть", "ru_ipa": "[аправ'эргнут']",
     "ru_def": "Доказать, что что-то неверно.",
     "en_word": "Refute", "en_ipa": "/rɪˈfjuːt/",
     "en_def": "To prove that something is wrong."},
    {"ru_word": "Усва́ивать", "ru_ipa": "[усваиват']",
     "ru_def": "Понимать и запоминать новое.",
     "en_word": "Absorb", "en_ipa": "/əbˈzɔːb/",
     "en_def": "To learn or take in information."},
    {"ru_word": "Растя́гивать", "ru_ipa": "[раст'аг'иват']",
     "ru_def": "Делать длиннее во времени или пространстве.",
     "en_word": "Stretch", "en_ipa": "/stretʃ/",
     "en_def": "To extend something in length or duration."},

    # ─── Adjectives ─────────────────────────────────────────────────────
    {"ru_word": "И́скренний", "ru_ipa": "[искр'ин'ий]",
     "ru_def": "Тот, кто говорит и чувствует по-настоящему.",
     "en_word": "Sincere", "en_ipa": "/sɪnˈsɪər/",
     "en_def": "Honest and truthful in feelings."},
    {"ru_word": "Глубо́кий", "ru_ipa": "[глубокий]",
     "ru_def": "Не поверхностный, имеющий смысл.",
     "en_word": "Profound", "en_ipa": "/prəˈfaʊnd/",
     "en_def": "Showing great depth of meaning or feeling."},
    {"ru_word": "Обы́денный", "ru_ipa": "[абыд'иный]",
     "ru_def": "Обычный, не выдающийся.",
     "en_word": "Mundane", "en_ipa": "/mʌnˈdeɪn/",
     "en_def": "Ordinary, lacking excitement."},
    {"ru_word": "Хру́пкий", "ru_ipa": "[хрупк'ий]",
     "ru_def": "Легко ломается или разрушается.",
     "en_word": "Fragile", "en_ipa": "/ˈfrædʒaɪl/",
     "en_def": "Easily broken or damaged."},
    {"ru_word": "Изы́сканный", "ru_ipa": "[изысканый]",
     "ru_def": "Тонкий и красивый по вкусу.",
     "en_word": "Exquisite", "en_ipa": "/ɪkˈskwɪzɪt/",
     "en_def": "Extremely beautiful or delicate."},
    {"ru_word": "Скро́мный", "ru_ipa": "[скромный]",
     "ru_def": "Без лишней гордости.",
     "en_word": "Humble", "en_ipa": "/ˈhʌmbəl/",
     "en_def": "Modest, not arrogant."},
    {"ru_word": "Ще́дрый", "ru_ipa": "[щ'эдрый]",
     "ru_def": "Готовый легко делиться.",
     "en_word": "Generous", "en_ipa": "/ˈdʒenərəs/",
     "en_def": "Willing to give freely."},
    {"ru_word": "Бесстра́шный", "ru_ipa": "[б'исстрашный]",
     "ru_def": "Тот, кто не боится трудностей.",
     "en_word": "Fearless", "en_ipa": "/ˈfɪərləs/",
     "en_def": "Without fear; brave."},
    {"ru_word": "Внима́тельный", "ru_ipa": "[вн'имат'ил'ный]",
     "ru_def": "Замечает детали и заботится.",
     "en_word": "Attentive", "en_ipa": "/əˈtentɪv/",
     "en_def": "Paying close attention; thoughtful."},
    {"ru_word": "Споко́йный", "ru_ipa": "[спакойный]",
     "ru_def": "Не нервничает, уверенный.",
     "en_word": "Composed", "en_ipa": "/kəmˈpoʊzd/",
     "en_def": "Calm and in control of yourself."},

    {"ru_word": "Изобрета́тельный", "ru_ipa": "[изабр'итат'ил'ный]",
     "ru_def": "Придумывает нестандартные решения.",
     "en_word": "Resourceful", "en_ipa": "/rɪˈsɔːsfəl/",
     "en_def": "Good at finding clever ways to solve problems."},
    {"ru_word": "Энерги́чный", "ru_ipa": "[энэрг'ич'ный]",
     "ru_def": "Полный сил и движения.",
     "en_word": "Vigorous", "en_ipa": "/ˈvɪɡərəs/",
     "en_def": "Full of energy and strength."},
    {"ru_word": "Любозна́тельный", "ru_ipa": "[любазнат'ил'ный]",
     "ru_def": "Любящий узнавать новое.",
     "en_word": "Inquisitive", "en_ipa": "/ɪnˈkwɪzɪtɪv/",
     "en_def": "Eager to learn or know."},
    {"ru_word": "Великоле́пный", "ru_ipa": "[в'ил'икал'эпный]",
     "ru_def": "Очень красивый, впечатляющий.",
     "en_word": "Magnificent", "en_ipa": "/mæɡˈnɪfɪsənt/",
     "en_def": "Extremely impressive or beautiful."},
    {"ru_word": "То́нкий", "ru_ipa": "[тонк'ий]",
     "ru_def": "Едва заметный, но важный.",
     "en_word": "Subtle", "en_ipa": "/ˈsʌtəl/",
     "en_def": "Slight and not obvious."},
    {"ru_word": "Очеви́дный", "ru_ipa": "[ач'ив'идный]",
     "ru_def": "Ясный и понятный сразу.",
     "en_word": "Evident", "en_ipa": "/ˈevɪdənt/",
     "en_def": "Easy to see or understand."},
    {"ru_word": "Двусмы́сленный", "ru_ipa": "[двусмысл'иный]",
     "ru_def": "Может пониматься по-разному.",
     "en_word": "Ambiguous", "en_ipa": "/æmˈbɪɡjuəs/",
     "en_def": "Having more than one possible meaning."},
    {"ru_word": "Безмяте́жный", "ru_ipa": "[б'измит'эжный]",
     "ru_def": "Глубоко спокойный и мирный.",
     "en_word": "Serene", "en_ipa": "/səˈriːn/",
     "en_def": "Calm, peaceful, and untroubled."},
    {"ru_word": "Ую́тный", "ru_ipa": "[уйутный]",
     "ru_def": "Дающий ощущение тепла и удобства.",
     "en_word": "Cozy", "en_ipa": "/ˈkoʊzi/",
     "en_def": "Giving a feeling of warmth and comfort."},
    {"ru_word": "Пра́здничный", "ru_ipa": "[празн'ич'ный]",
     "ru_def": "Радостный, как в особый день.",
     "en_word": "Festive", "en_ipa": "/ˈfestɪv/",
     "en_def": "Cheerful and full of celebration."},

    # ─── Useful nouns ───────────────────────────────────────────────────
    {"ru_word": "Привя́занность", "ru_ipa": "[пр'ив'азанаст']",
     "ru_def": "Тёплая связь с кем-то или чем-то.",
     "en_word": "Attachment", "en_ipa": "/əˈtætʃmənt/",
     "en_def": "A strong feeling of affection or loyalty."},
    {"ru_word": "Уси́лие", "ru_ipa": "[ус'ил'ийэ]",
     "ru_def": "Энергия, потраченная на что-то.",
     "en_word": "Effort", "en_ipa": "/ˈefət/",
     "en_def": "Energy used to achieve something."},
    {"ru_word": "Уве́ренность", "ru_ipa": "[ув'эринаст']",
     "ru_def": "Знание, что ты справишься.",
     "en_word": "Confidence", "en_ipa": "/ˈkɒnfɪdəns/",
     "en_def": "Belief in your own ability."},
    {"ru_word": "Гармо́ния", "ru_ipa": "[гармон'ийа]",
     "ru_def": "Согласие частей друг с другом.",
     "en_word": "Harmony", "en_ipa": "/ˈhɑːməni/",
     "en_def": "A pleasing arrangement of parts."},
    {"ru_word": "Ги́бкость", "ru_ipa": "[г'ипкаст']",
     "ru_def": "Способность легко меняться.",
     "en_word": "Flexibility", "en_ipa": "/ˌfleksəˈbɪlɪti/",
     "en_def": "The ability to adapt easily."},
    {"ru_word": "Я́сность", "ru_ipa": "[йаснаст']",
     "ru_def": "Когда всё понятно и просто.",
     "en_word": "Clarity", "en_ipa": "/ˈklærɪti/",
     "en_def": "The quality of being clear and easy to understand."},
    {"ru_word": "Це́льность", "ru_ipa": "[цэл'наст']",
     "ru_def": "Соответствие слов и дел.",
     "en_word": "Integrity", "en_ipa": "/ɪnˈteɡrɪti/",
     "en_def": "The quality of being honest and having strong morals."},
    {"ru_word": "Любозна́тельность", "ru_ipa": "[любазнат'ил'наст']",
     "ru_def": "Тяга к знаниям.",
     "en_word": "Inquisitiveness", "en_ipa": "/ɪnˈkwɪzɪtɪvnəs/",
     "en_def": "Eagerness to learn."},
    {"ru_word": "Восприя́тие", "ru_ipa": "[васпр'ийат'ийэ]",
     "ru_def": "Как ты видишь и понимаешь мир.",
     "en_word": "Perception", "en_ipa": "/pəˈsepʃən/",
     "en_def": "The way you understand or interpret something."},
    {"ru_word": "Ощуще́ние", "ru_ipa": "[ащ'ущ'эн'ийэ]",
     "ru_def": "То, что ты чувствуешь телом или душой.",
     "en_word": "Sensation", "en_ipa": "/senˈseɪʃən/",
     "en_def": "A physical or mental feeling."},

    {"ru_word": "Влече́ние", "ru_ipa": "[вл'ич'эн'ийэ]",
     "ru_def": "Сильный интерес к человеку или делу.",
     "en_word": "Attraction", "en_ipa": "/əˈtrækʃən/",
     "en_def": "A strong pull towards someone or something."},
    {"ru_word": "Знако́мство", "ru_ipa": "[знакомства]",
     "ru_def": "Первый контакт с чем-то новым.",
     "en_word": "Acquaintance", "en_ipa": "/əˈkweɪntəns/",
     "en_def": "Slight knowledge of a person or thing."},
    {"ru_word": "Воспомина́ние", "ru_ipa": "[васпам'инан'ийэ]",
     "ru_def": "Кусочек прошлого в памяти.",
     "en_word": "Memory", "en_ipa": "/ˈmeməri/",
     "en_def": "Something remembered from the past."},
    {"ru_word": "Тишина́", "ru_ipa": "[т'ишына]",
     "ru_def": "Отсутствие звуков и шума.",
     "en_word": "Silence", "en_ipa": "/ˈsaɪləns/",
     "en_def": "The absence of sound."},
    {"ru_word": "Грани́ца", "ru_ipa": "[гран'ица]",
     "ru_def": "Линия, за которую не переходят.",
     "en_word": "Boundary", "en_ipa": "/ˈbaʊndəri/",
     "en_def": "A line that marks a limit."},
    {"ru_word": "Привы́чка", "ru_ipa": "[пр'ивычка]",
     "ru_def": "Регулярное действие, которое стало автоматическим.",
     "en_word": "Routine", "en_ipa": "/ruːˈtiːn/",
     "en_def": "A regular way of doing things."},
    {"ru_word": "Назначе́ние", "ru_ipa": "[назнач'эн'ийэ]",
     "ru_def": "Цель, ради которой что-то существует.",
     "en_word": "Purpose", "en_ipa": "/ˈpɜːpəs/",
     "en_def": "The reason for which something exists."},
    {"ru_word": "Преиму́щество", "ru_ipa": "[пр'иимущ'иства]",
     "ru_def": "То, что даёт тебе плюс.",
     "en_word": "Advantage", "en_ipa": "/ədˈvɑːntɪdʒ/",
     "en_def": "Something that gives you a better chance."},
    {"ru_word": "Недоста́ток", "ru_ipa": "[н'идастатак]",
     "ru_def": "Слабая или плохая сторона.",
     "en_word": "Drawback", "en_ipa": "/ˈdrɔːbæk/",
     "en_def": "A negative side of something."},
    {"ru_word": "Достиже́ние", "ru_ipa": "[даст'ижэн'ийэ]",
     "ru_def": "Результат больших усилий.",
     "en_word": "Accomplishment", "en_ipa": "/əˈkʌmplɪʃmənt/",
     "en_def": "Something successfully completed."},

    {"ru_word": "Свобо́да", "ru_ipa": "[свабода]",
     "ru_def": "Возможность выбирать без принуждения.",
     "en_word": "Freedom", "en_ipa": "/ˈfriːdəm/",
     "en_def": "The power to act or speak without restriction."},
    {"ru_word": "Отве́тственность", "ru_ipa": "[атв'эцтв'инаст']",
     "ru_def": "Готовность отвечать за свои действия.",
     "en_word": "Responsibility", "en_ipa": "/rɪˌspɒnsɪˈbɪlɪti/",
     "en_def": "The duty to deal with something."},
    {"ru_word": "Сло́во", "ru_ipa": "[слова]",
     "ru_def": "Обещание, которое стоит сдержать.",
     "en_word": "Promise", "en_ipa": "/ˈprɒmɪs/",
     "en_def": "A statement that you will do something."},
    {"ru_word": "Уваже́ние", "ru_ipa": "[уважэн'ийэ]",
     "ru_def": "Признание ценности человека.",
     "en_word": "Respect", "en_ipa": "/rɪˈspekt/",
     "en_def": "A feeling of admiration for someone."},
    {"ru_word": "Дове́рие", "ru_ipa": "[дав'эр'ийэ]",
     "ru_def": "Вера в честность другого человека.",
     "en_word": "Trust", "en_ipa": "/trʌst/",
     "en_def": "Firm belief in someone's reliability."},
    {"ru_word": "Соглаше́ние", "ru_ipa": "[саглашэн'ийэ]",
     "ru_def": "Когда стороны договорились о чём-то.",
     "en_word": "Agreement", "en_ipa": "/əˈɡriːmənt/",
     "en_def": "A decision shared by two or more people."},
    {"ru_word": "Препя́тствие", "ru_ipa": "[пр'ип'ацтв'ийэ]",
     "ru_def": "Что-то, что мешает достичь цели.",
     "en_word": "Hindrance", "en_ipa": "/ˈhɪndrəns/",
     "en_def": "Something that makes progress more difficult."},
    {"ru_word": "Успе́х", "ru_ipa": "[усп'эх]",
     "ru_def": "Достижение того, чего хотел.",
     "en_word": "Success", "en_ipa": "/səkˈses/",
     "en_def": "Achieving what you set out to do."},
    {"ru_word": "Откры́тие", "ru_ipa": "[аткрыт'ийэ]",
     "ru_def": "Находка чего-то нового и важного.",
     "en_word": "Discovery", "en_ipa": "/dɪˈskʌvəri/",
     "en_def": "Finding something previously unknown."},
    {"ru_word": "Соревнова́ние", "ru_ipa": "[сар'ивнаван'ийэ]",
     "ru_def": "Борьба за лучший результат.",
     "en_word": "Competition", "en_ipa": "/ˌkɒmpəˈtɪʃən/",
     "en_def": "A contest to determine who is best."},

    # ─── Everyday / lifestyle ────────────────────────────────────────────
    {"ru_word": "За́втрак", "ru_ipa": "[зафтрак]",
     "ru_def": "Утренний приём пищи.",
     "en_word": "Breakfast", "en_ipa": "/ˈbrekfəst/",
     "en_def": "The morning meal."},
    {"ru_word": "Прогу́лка", "ru_ipa": "[прагулка]",
     "ru_def": "Спокойная ходьба ради удовольствия.",
     "en_word": "Stroll", "en_ipa": "/stroʊl/",
     "en_def": "A relaxed walk."},
    {"ru_word": "Бесе́да", "ru_ipa": "[б'ис'эда]",
     "ru_def": "Дружеский разговор без спешки.",
     "en_word": "Conversation", "en_ipa": "/ˌkɒnvəˈseɪʃən/",
     "en_def": "An informal exchange of thoughts."},
    {"ru_word": "Ую́т", "ru_ipa": "[уйут]",
     "ru_def": "Чувство домашнего тепла и комфорта.",
     "en_word": "Coziness", "en_ipa": "/ˈkoʊzinəs/",
     "en_def": "A feeling of warm comfort at home."},
    {"ru_word": "Зака́т", "ru_ipa": "[закат]",
     "ru_def": "Момент, когда солнце уходит за горизонт.",
     "en_word": "Sunset", "en_ipa": "/ˈsʌnset/",
     "en_def": "When the sun goes below the horizon."},
    {"ru_word": "Рассве́т", "ru_ipa": "[рассв'эт]",
     "ru_def": "Время, когда солнце появляется.",
     "en_word": "Dawn", "en_ipa": "/dɔːn/",
     "en_def": "The first light of day."},
    {"ru_word": "Су́мерки", "ru_ipa": "[сум'ирк'и]",
     "ru_def": "Полутёмное время между днём и ночью.",
     "en_word": "Twilight", "en_ipa": "/ˈtwaɪlaɪt/",
     "en_def": "The soft light just after sunset."},
    {"ru_word": "Прохла́да", "ru_ipa": "[прахлада]",
     "ru_def": "Лёгкий приятный холод.",
     "en_word": "Coolness", "en_ipa": "/ˈkuːlnəs/",
     "en_def": "A pleasant slight coldness."},
    {"ru_word": "Све́жесть", "ru_ipa": "[св'эжыст']",
     "ru_def": "Чистота воздуха или новизна вкуса.",
     "en_word": "Freshness", "en_ipa": "/ˈfreʃnəs/",
     "en_def": "The quality of being new, clean, or pure."},
    {"ru_word": "Арома́т", "ru_ipa": "[арамат]",
     "ru_def": "Приятный запах.",
     "en_word": "Aroma", "en_ipa": "/əˈroʊmə/",
     "en_def": "A pleasant smell."},

    {"ru_word": "Намёк", "ru_ipa": "[нам'ок]",
     "ru_def": "Неявный знак или подсказка.",
     "en_word": "Hint", "en_ipa": "/hɪnt/",
     "en_def": "An indirect suggestion."},
    {"ru_word": "Зага́дка", "ru_ipa": "[загатка]",
     "ru_def": "То, что нужно разгадать.",
     "en_word": "Riddle", "en_ipa": "/ˈrɪdəl/",
     "en_def": "A puzzle phrased as a question."},
    {"ru_word": "Сюрпри́з", "ru_ipa": "[с'урпр'ис]",
     "ru_def": "Что-то неожиданное и приятное.",
     "en_word": "Surprise", "en_ipa": "/səˈpraɪz/",
     "en_def": "An unexpected event."},
    {"ru_word": "Награ́да", "ru_ipa": "[награда]",
     "ru_def": "То, что получаешь за заслуги.",
     "en_word": "Reward", "en_ipa": "/rɪˈwɔːd/",
     "en_def": "Something given for an achievement."},
    {"ru_word": "Подде́ржка", "ru_ipa": "[падд'эршка]",
     "ru_def": "Помощь словом или делом.",
     "en_word": "Support", "en_ipa": "/səˈpɔːt/",
     "en_def": "Help or encouragement."},
    {"ru_word": "Привы́чка", "ru_ipa": "[пр'ивычка]",
     "ru_def": "То, что делается каждый день автоматически.",
     "en_word": "Custom", "en_ipa": "/ˈkʌstəm/",
     "en_def": "A traditional way of behaving."},
    {"ru_word": "До́лг", "ru_ipa": "[долк]",
     "ru_def": "То, что ты обязан сделать.",
     "en_word": "Duty", "en_ipa": "/ˈdjuːti/",
     "en_def": "Something you must do."},
    {"ru_word": "Це́ль", "ru_ipa": "[цэл']",
     "ru_def": "То, к чему ты стремишься.",
     "en_word": "Goal", "en_ipa": "/ɡoʊl/",
     "en_def": "Something you aim for."},
    {"ru_word": "Стремле́ние", "ru_ipa": "[стр'имл'эн'ийэ]",
     "ru_def": "Сильное желание добиться чего-то.",
     "en_word": "Aspiration", "en_ipa": "/ˌæspəˈreɪʃən/",
     "en_def": "A strong hope or desire."},
    {"ru_word": "Тала́нт", "ru_ipa": "[талант]",
     "ru_def": "Природная способность к делу.",
     "en_word": "Talent", "en_ipa": "/ˈtælənt/",
     "en_def": "A natural ability to do something well."},
]
